# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `gameEnded`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")
const GameResultMessage = preload("game_result_message.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "gameEnded"

static var _definition = null

## `results`: array<nested<gameResult>>.
var results: Array = []


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["results", Contract.array_of(Contract.nested(GameResultMessage.definition()))],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["results"] = Payloads.map_list(results, func(x0): return x0.to_payload())
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.results = Payloads.map_list(payload.get("results"), func(x0): return GameResultMessage.from_payload(x0))
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
