# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `input`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "input"

static var _definition = null

## `up`: bool.
var up: bool = false
## `down`: bool.
var down: bool = false
## `left`: bool.
var left: bool = false
## `right`: bool.
var right: bool = false
## `rotation`: fixed:2.
var rotation: float = 0.0
## `shooting`: bool.
var shooting: bool = false


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["up", Contract.bool_()],
			["down", Contract.bool_()],
			["left", Contract.bool_()],
			["right", Contract.bool_()],
			["rotation", Contract.fixed(2)],
			["shooting", Contract.bool_()],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["up"] = up
	payload["down"] = down
	payload["left"] = left
	payload["right"] = right
	payload["rotation"] = rotation
	payload["shooting"] = shooting
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.up = payload.get("up")
	message.down = payload.get("down")
	message.left = payload.get("left")
	message.right = payload.get("right")
	message.rotation = payload.get("rotation")
	message.shooting = payload.get("shooting")
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
