# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `playerJoined`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "playerJoined"

static var _definition = null

## `playerId`: string.
var player_id: String = ""
## `playerName`: string.
var player_name: String = ""


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["playerId", Contract.string()],
			["playerName", Contract.string()],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["playerId"] = player_id
	payload["playerName"] = player_name
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.player_id = payload.get("playerId")
	message.player_name = payload.get("playerName")
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
