# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `shooterCreateOptions`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "shooterCreateOptions"

static var _definition = null

## `roomName`: optional<string>.
var room_name = null
## `maxPlayers`: uint8.
var max_players: int = 0
## `isPrivate`: bool.
var is_private: bool = false


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["roomName", Contract.optional_of(Contract.string())],
			["maxPlayers", Contract.uint8()],
			["isPrivate", Contract.bool_()],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	if room_name != null:
		payload["roomName"] = room_name
	payload["maxPlayers"] = max_players
	payload["isPrivate"] = is_private
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	if payload.get("roomName") != null:
		message.room_name = payload["roomName"]
	message.max_players = payload.get("maxPlayers")
	message.is_private = payload.get("isPrivate")
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
