# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `Bullet`.

## The class's name on the wire.
const SCHEMA_NAME := "Bullet"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["ownerId", "string", "owner_id"],
	["x", "fixed:1", "x"],
	["y", "fixed:1", "y"],
]

## `ownerId` changed; emitted after the frame is applied.
signal owner_id_changed(value: String, previous: String)
## `x` changed; emitted after the frame is applied.
signal x_changed(value: float, previous: float)
## `y` changed; emitted after the frame is applied.
signal y_changed(value: float, previous: float)

## `ownerId`: string.
var owner_id: String = ""
## `x`: fixed:1.
var x: float = 0.0
## `y`: fixed:1.
var y: float = 0.0
