# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `Enemy`.

## The class's name on the wire.
const SCHEMA_NAME := "Enemy"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["x", "fixed:1", "x"],
	["y", "fixed:1", "y"],
	["health", "uint8", "health"],
]

## `x` changed; emitted after the frame is applied.
signal x_changed(value: float, previous: float)
## `y` changed; emitted after the frame is applied.
signal y_changed(value: float, previous: float)
## `health` changed; emitted after the frame is applied.
signal health_changed(value: int, previous: int)

## `x`: fixed:1.
var x: float = 0.0
## `y`: fixed:1.
var y: float = 0.0
## `health`: uint8.
var health: int = 0
