# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `GameState`.

const MapSchema = preload("res://addons/bungohan/replica/map_schema.gd")

## The class's name on the wire.
const SCHEMA_NAME := "GameState"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["players", "schemaMap<string,Player>", "players"],
	["enemies", "schemaMap<uint32,Enemy>", "enemies"],
	["bullets", "schemaMap<uint32,Bullet>", "bullets"],
	["loot", "schemaMap<uint32,Loot>", "loot"],
	["roomCode", "string", "room_code"],
	["roomName", "string", "room_name"],
	["hostId", "string", "host_id"],
	["gameTime", "uint16", "game_time"],
	["gameStatus", "string", "game_status"],
	["maxPlayers", "uint8", "max_players"],
	["canStart", "bool", "can_start"],
]

## `roomCode` changed; emitted after the frame is applied.
signal room_code_changed(value: String, previous: String)
## `roomName` changed; emitted after the frame is applied.
signal room_name_changed(value: String, previous: String)
## `hostId` changed; emitted after the frame is applied.
signal host_id_changed(value: String, previous: String)
## `gameTime` changed; emitted after the frame is applied.
signal game_time_changed(value: int, previous: int)
## `gameStatus` changed; emitted after the frame is applied.
signal game_status_changed(value: String, previous: String)
## `maxPlayers` changed; emitted after the frame is applied.
signal max_players_changed(value: int, previous: int)
## `canStart` changed; emitted after the frame is applied.
signal can_start_changed(value: bool, previous: bool)

## `players`: schemaMap<string,Player>.
var players = MapSchema.new("schemaMap<string,Player>")
## `enemies`: schemaMap<uint32,Enemy>.
var enemies = MapSchema.new("schemaMap<uint32,Enemy>")
## `bullets`: schemaMap<uint32,Bullet>.
var bullets = MapSchema.new("schemaMap<uint32,Bullet>")
## `loot`: schemaMap<uint32,Loot>.
var loot = MapSchema.new("schemaMap<uint32,Loot>")
## `roomCode`: string.
var room_code: String = ""
## `roomName`: string.
var room_name: String = ""
## `hostId`: string.
var host_id: String = ""
## `gameTime`: uint16.
var game_time: int = 0
## `gameStatus`: string.
var game_status: String = ""
## `maxPlayers`: uint8.
var max_players: int = 0
## `canStart`: bool.
var can_start: bool = false
