# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `LobbyState`.

const MapSchema = preload("res://addons/bungohan/replica/map_schema.gd")

## The class's name on the wire.
const SCHEMA_NAME := "LobbyState"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["rooms", "schemaMap<string,RoomInfo>", "rooms"],
]

## `rooms`: schemaMap<string,RoomInfo>.
var rooms = MapSchema.new("schemaMap<string,RoomInfo>")
