# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `Loot`.

## The class's name on the wire.
const SCHEMA_NAME := "Loot"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["x", "fixed:1", "x"],
	["y", "fixed:1", "y"],
	["value", "uint8", "value"],
]

## `x` changed; emitted after the frame is applied.
signal x_changed(value: float, previous: float)
## `y` changed; emitted after the frame is applied.
signal y_changed(value: float, previous: float)
## `value` changed; emitted after the frame is applied.
signal value_changed(value: int, previous: int)

## `x`: fixed:1.
var x: float = 0.0
## `y`: fixed:1.
var y: float = 0.0
## `value`: uint8.
var value: int = 0
