# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `Player`.

## The class's name on the wire.
const SCHEMA_NAME := "Player"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["name", "string", "name"],
	["color", "string", "color"],
	["x", "fixed:1", "x"],
	["y", "fixed:1", "y"],
	["rotation", "fixed:2", "rotation"],
	["score", "int32", "score"],
	["health", "uint8", "health"],
	["isDead", "bool", "is_dead"],
	["isReady", "bool", "is_ready"],
]

## `name` changed; emitted after the frame is applied.
signal name_changed(value: String, previous: String)
## `color` changed; emitted after the frame is applied.
signal color_changed(value: String, previous: String)
## `x` changed; emitted after the frame is applied.
signal x_changed(value: float, previous: float)
## `y` changed; emitted after the frame is applied.
signal y_changed(value: float, previous: float)
## `rotation` changed; emitted after the frame is applied.
signal rotation_changed(value: float, previous: float)
## `score` changed; emitted after the frame is applied.
signal score_changed(value: int, previous: int)
## `health` changed; emitted after the frame is applied.
signal health_changed(value: int, previous: int)
## `isDead` changed; emitted after the frame is applied.
signal is_dead_changed(value: bool, previous: bool)
## `isReady` changed; emitted after the frame is applied.
signal is_ready_changed(value: bool, previous: bool)

## `name`: string.
var name: String = ""
## `color`: string.
var color: String = ""
## `x`: fixed:1.
var x: float = 0.0
## `y`: fixed:1.
var y: float = 0.0
## `rotation`: fixed:2.
var rotation: float = 0.0
## `score`: int32.
var score: int = 0
## `health`: uint8.
var health: int = 0
## `isDead`: bool.
var is_dead: bool = false
## `isReady`: bool.
var is_ready: bool = false
