# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `RoomInfo`.

## The class's name on the wire.
const SCHEMA_NAME := "RoomInfo"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["name", "string", "name"],
	["code", "string", "code"],
	["hostName", "string", "host_name"],
	["playerCount", "uint8", "player_count"],
	["maxPlayers", "uint8", "max_players"],
	["status", "string", "status"],
]

## `name` changed; emitted after the frame is applied.
signal name_changed(value: String, previous: String)
## `code` changed; emitted after the frame is applied.
signal code_changed(value: String, previous: String)
## `hostName` changed; emitted after the frame is applied.
signal host_name_changed(value: String, previous: String)
## `playerCount` changed; emitted after the frame is applied.
signal player_count_changed(value: int, previous: int)
## `maxPlayers` changed; emitted after the frame is applied.
signal max_players_changed(value: int, previous: int)
## `status` changed; emitted after the frame is applied.
signal status_changed(value: String, previous: String)

## `name`: string.
var name: String = ""
## `code`: string.
var code: String = ""
## `hostName`: string.
var host_name: String = ""
## `playerCount`: uint8.
var player_count: int = 0
## `maxPlayers`: uint8.
var max_players: int = 0
## `status`: string.
var status: String = ""
