# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `Interop.Player`.

const SetSchema = preload("res://addons/bungohan/replica/set_schema.gd")

## The class's name on the wire.
const SCHEMA_NAME := "Interop.Player"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["name", "string", "name"],
	["x", "fixed:2", "x"],
	["y", "fixed:2", "y"],
	["score", "int32", "score"],
	["alive", "bool", "alive"],
	["tags", "set<string>", "tags"],
]

## `name` changed; emitted after the frame is applied.
signal name_changed(value: String, previous: String)
## `x` changed; emitted after the frame is applied.
signal x_changed(value: float, previous: float)
## `y` changed; emitted after the frame is applied.
signal y_changed(value: float, previous: float)
## `score` changed; emitted after the frame is applied.
signal score_changed(value: int, previous: int)
## `alive` changed; emitted after the frame is applied.
signal alive_changed(value: bool, previous: bool)

## `name`: string.
var name: String = ""
## `x`: fixed:2.
var x: float = 0.0
## `y`: fixed:2.
var y: float = 0.0
## `score`: int32.
var score: int = 0
## `alive`: bool.
var alive: bool = false
## `tags`: set<string>.
var tags = SetSchema.new("set<string>")
