# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `Interop.State`.

const ArraySchema = preload("res://addons/bungohan/replica/array_schema.gd")
const MapSchema = preload("res://addons/bungohan/replica/map_schema.gd")

## The class's name on the wire.
const SCHEMA_NAME := "Interop.State"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["turn", "uint32", "turn"],
	["label", "string", "label"],
	["players", "schemaMap<string,Interop.Player>", "players"],
	["log", "array<string>", "log"],
]

## `turn` changed; emitted after the frame is applied.
signal turn_changed(value: int, previous: int)
## `label` changed; emitted after the frame is applied.
signal label_changed(value: String, previous: String)

## `turn`: uint32.
var turn: int = 0
## `label`: string.
var label: String = ""
## `players`: schemaMap<string,Interop.Player>.
var players = MapSchema.new("schemaMap<string,Interop.Player>")
## `log`: array<string>.
var log = ArraySchema.new("array<string>")
