# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract `lobbyContract`.

const Result = preload("res://addons/bungohan/protocol/result.gd")
const ErrorMessage = preload("../messages/error_message.gd")
const JoinByCodeMessage = preload("../messages/join_by_code_message.gd")
const RefreshRoomsMessage = preload("../messages/refresh_rooms_message.gd")
const RoomFoundMessage = preload("../messages/room_found_message.gd")

## The contract hash this client was built against: sent in JOIN and
## compared with the handshake's. Message ids are not generated: they
## come from the handshake and are resolved by name.
const HASH := "4342ab15"
## Client → server messages, by name.
const CLIENT := {
	"refreshRooms": RefreshRoomsMessage,
	"joinByCode": JoinByCodeMessage,
}
## Server → client messages, by name.
const SERVER := {
	"roomFound": RoomFoundMessage,
	"error": ErrorMessage,
}


## Decodes a server message by name (resolved from its id through the
## handshake's table): a Result holding the message.
static func decode_server(codec, name: String, body: PackedByteArray):
	return _decode(SERVER, codec, name, body)


static func decode_client(codec, name: String, body: PackedByteArray):
	return _decode(CLIENT, codec, name, body)


static func _decode(table: Dictionary, codec, name: String, body: PackedByteArray):
	if not table.has(name):
		return Result.failure(Result.DECODE_FAILED, "no message named " + name)
	return table[name].decode(codec, body)
