# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract `shooterContract`.

const Result = preload("res://addons/bungohan/protocol/result.gd")
const GameEndedMessage = preload("../messages/game_ended_message.gd")
const GameStartedMessage = preload("../messages/game_started_message.gd")
const InputMessage = preload("../messages/input_message.gd")
const PlayerJoinedMessage = preload("../messages/player_joined_message.gd")
const PlayerLeftMessage = preload("../messages/player_left_message.gd")
const ReadyMessage = preload("../messages/ready_message.gd")
const StartGameMessage = preload("../messages/start_game_message.gd")

## The contract hash this client was built against: sent in JOIN and
## compared with the handshake's. Message ids are not generated: they
## come from the handshake and are resolved by name.
const HASH := "f671e798"
## Client → server messages, by name.
const CLIENT := {
	"input": InputMessage,
	"ready": ReadyMessage,
	"startGame": StartGameMessage,
}
## Server → client messages, by name.
const SERVER := {
	"playerJoined": PlayerJoinedMessage,
	"playerLeft": PlayerLeftMessage,
	"gameStarted": GameStartedMessage,
	"gameEnded": GameEndedMessage,
}


## Decodes a server message by name (resolved from its id through the
## handshake's table): a Result holding the message.
static func decode_server(codec, name: String, body: PackedByteArray):
	return _decode(SERVER, codec, name, body)


static func decode_client(codec, name: String, body: PackedByteArray):
	return _decode(CLIENT, codec, name, body)


static func _decode(table: Dictionary, codec, name: String, body: PackedByteArray):
	if not table.has(name):
		return Result.failure(Result.DECODE_FAILED, "no message named " + name)
	return table[name].decode(codec, body)
