# Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `everything`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")
const PointMessage = preload("point_message.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "everything"
## Values of `color`, in index order.
const COLOR_VALUES := ["red", "green", "dark blue"]
## Values of `level`, in index order.
const LEVEL_VALUES := [1, 5, 10]
## Values of `maybeColor`, in index order.
const MAYBE_COLOR_VALUES := ["north", "south"]
## Values of `palette`, in index order.
const PALETTE_VALUES := ["red", "blue"]

static var _definition = null

## `i8`: int8.
var i8: int = 0
## `i16`: int16.
var i16: int = 0
## `i32`: int32.
var i32: int = 0
## `u8`: uint8.
var u8: int = 0
## `u16`: uint16.
var u16: int = 0
## `u32`: uint32.
var u32: int = 0
## `f32`: float32.
var f32: float = 0.0
## `f64`: float64.
var f64: float = 0.0
## `fx`: fixed:3.
var fx: float = 0.0
## `text`: string.
var text: String = ""
## `flag`: bool.
var flag: bool = false
## `color`: enum["red"|"green"|"dark blue"].
var color = "red"
## `level`: enum[1|5|10].
var level = 1
## `list`: array<int16>.
var list: Array = []
## `names`: map<string>.
var names: Dictionary = {}
## `maybe`: optional<fixed:1>.
var maybe = null
## `maybeFlag`: optional<bool>.
var maybe_flag = null
## `maybeColor`: optional<enum["north"|"south"]>.
var maybe_color = null
## `maybePoint`: optional<nested<point>>.
var maybe_point = null
## `holes`: array<optional<uint8>>.
var holes: Array = []
## `sparse`: map<optional<bool>>.
var sparse: Dictionary = {}
## `point`: nested<point>.
var point = PointMessage.new()
## `path`: array<nested<point>>.
var path: Array = []
## `grid`: array<array<float64>>.
var grid: Array = []
## `tagged`: map<array<nested<point>>>.
var tagged: Dictionary = {}
## `palette`: array<enum["red"|"blue"]>.
var palette: Array = []
## `definition`: string.
var definition_: String = ""
## `encode`: bool.
var encode_: bool = false


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["i8", Contract.int8()],
			["i16", Contract.int16()],
			["i32", Contract.int32()],
			["u8", Contract.uint8()],
			["u16", Contract.uint16()],
			["u32", Contract.uint32()],
			["f32", Contract.float32()],
			["f64", Contract.float64()],
			["fx", Contract.fixed(3)],
			["text", Contract.string()],
			["flag", Contract.bool_()],
			["color", Contract.enum_of(["red", "green", "dark blue"])],
			["level", Contract.enum_of([1, 5, 10])],
			["list", Contract.array_of(Contract.int16())],
			["names", Contract.map_of(Contract.string())],
			["maybe", Contract.optional_of(Contract.fixed(1))],
			["maybeFlag", Contract.optional_of(Contract.bool_())],
			["maybeColor", Contract.optional_of(Contract.enum_of(["north", "south"]))],
			["maybePoint", Contract.optional_of(Contract.nested(PointMessage.definition()))],
			["holes", Contract.array_of(Contract.optional_of(Contract.uint8()))],
			["sparse", Contract.map_of(Contract.optional_of(Contract.bool_()))],
			["point", Contract.nested(PointMessage.definition())],
			["path", Contract.array_of(Contract.nested(PointMessage.definition()))],
			["grid", Contract.array_of(Contract.array_of(Contract.float64()))],
			["tagged", Contract.map_of(Contract.array_of(Contract.nested(PointMessage.definition())))],
			["palette", Contract.array_of(Contract.enum_of(["red", "blue"]))],
			["definition", Contract.string()],
			["encode", Contract.bool_()],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["i8"] = i8
	payload["i16"] = i16
	payload["i32"] = i32
	payload["u8"] = u8
	payload["u16"] = u16
	payload["u32"] = u32
	payload["f32"] = f32
	payload["f64"] = f64
	payload["fx"] = fx
	payload["text"] = text
	payload["flag"] = flag
	payload["color"] = color
	payload["level"] = level
	payload["list"] = list.duplicate()
	payload["names"] = names.duplicate()
	if maybe != null:
		payload["maybe"] = maybe
	if maybe_flag != null:
		payload["maybeFlag"] = maybe_flag
	if maybe_color != null:
		payload["maybeColor"] = maybe_color
	if maybe_point != null:
		payload["maybePoint"] = maybe_point.to_payload()
	payload["holes"] = holes.duplicate()
	payload["sparse"] = sparse.duplicate()
	payload["point"] = point.to_payload()
	payload["path"] = Payloads.map_list(path, func(x0): return x0.to_payload())
	payload["grid"] = grid.duplicate()
	payload["tagged"] = Payloads.map_values(tagged, func(x0): return Payloads.map_list(x0, func(x1): return x1.to_payload()))
	payload["palette"] = palette.duplicate()
	payload["definition"] = definition_
	payload["encode"] = encode_
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.i8 = payload.get("i8")
	message.i16 = payload.get("i16")
	message.i32 = payload.get("i32")
	message.u8 = payload.get("u8")
	message.u16 = payload.get("u16")
	message.u32 = payload.get("u32")
	message.f32 = payload.get("f32")
	message.f64 = payload.get("f64")
	message.fx = payload.get("fx")
	message.text = payload.get("text")
	message.flag = payload.get("flag")
	message.color = payload.get("color")
	message.level = payload.get("level")
	message.list = Payloads.map_list(payload.get("list"), func(x0): return x0)
	message.names = Payloads.map_values(payload.get("names"), func(x0): return x0)
	if payload.get("maybe") != null:
		message.maybe = payload["maybe"]
	if payload.get("maybeFlag") != null:
		message.maybe_flag = payload["maybeFlag"]
	if payload.get("maybeColor") != null:
		message.maybe_color = payload["maybeColor"]
	if payload.get("maybePoint") != null:
		message.maybe_point = PointMessage.from_payload(payload["maybePoint"])
	message.holes = Payloads.map_list(payload.get("holes"), func(x0): return x0)
	message.sparse = Payloads.map_values(payload.get("sparse"), func(x0): return x0)
	message.point = PointMessage.from_payload(payload.get("point"))
	message.path = Payloads.map_list(payload.get("path"), func(x0): return PointMessage.from_payload(x0))
	message.grid = Payloads.map_list(payload.get("grid"), func(x0): return x0)
	message.tagged = Payloads.map_values(payload.get("tagged"), func(x0): return Payloads.map_list(x0, func(x1): return PointMessage.from_payload(x1)))
	message.palette = Payloads.map_list(payload.get("palette"), func(x0): return x0)
	message.definition_ = payload.get("definition")
	message.encode_ = payload.get("encode")
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
