# Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `lobby`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "lobby"
## Values of `map`, in index order.
const MAP_VALUES := ["dust", "ice"]

static var _definition = null

## `map`: enum["dust"|"ice"].
var map = "dust"
## `rounds`: uint8.
var rounds: int = 0
## `ranked`: bool.
var ranked: bool = false


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["map", Contract.enum_of(["dust", "ice"])],
			["rounds", Contract.uint8()],
			["ranked", Contract.bool_()],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["map"] = map
	payload["rounds"] = rounds
	payload["ranked"] = ranked
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.map = payload.get("map")
	message.rounds = payload.get("rounds")
	message.ranked = payload.get("ranked")
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
