# Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `seat`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")
const PointMessage = preload("point_message.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "seat"

static var _definition = null

## `name`: string.
var name: String = ""
## `team`: optional<uint8>.
var team = null
## `at`: nested<point>.
var at = PointMessage.new()


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["name", Contract.string()],
			["team", Contract.optional_of(Contract.uint8())],
			["at", Contract.nested(PointMessage.definition())],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["name"] = name
	if team != null:
		payload["team"] = team
	payload["at"] = at.to_payload()
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.name = payload.get("name")
	if payload.get("team") != null:
		message.team = payload["team"]
	message.at = PointMessage.from_payload(payload.get("at"))
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
