// <auto-generated>
// Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
// Do not edit: regenerate instead.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Bungohan.Protocol;

namespace Bungohan.Interop
{
    /// <summary>Contract <c>interopContract</c>.</summary>
    public static class InteropContract
    {
        /// <summary>
        /// The contract hash this client was built against: sent in JOIN and
        /// compared with the handshake's. Message ids are not generated: they
        /// come from the handshake and are resolved by name.
        /// </summary>
        public const string Hash = "eef98c28";

        /// <summary>Client → server messages, by name.</summary>
        public static readonly IReadOnlyDictionary<string, MessageDef> ClientMessages = new Dictionary<string, MessageDef>
        {
            ["move"] = MoveMessage.Definition,
            ["setName"] = SetNameMessage.Definition,
            ["addTag"] = AddTagMessage.Definition,
            ["bump"] = BumpMessage.Definition,
            ["requestDump"] = RequestDumpMessage.Definition,
            ["echo"] = EchoMessage.Definition,
            ["kickMe"] = KickMeMessage.Definition,
            ["dropMe"] = DropMeMessage.Definition,
        };

        /// <summary>Server → client messages, by name.</summary>
        public static readonly IReadOnlyDictionary<string, MessageDef> ServerMessages = new Dictionary<string, MessageDef>
        {
            ["welcome"] = WelcomeMessage.Definition,
            ["dump"] = DumpMessage.Definition,
            ["echoed"] = EchoedMessage.Definition,
        };

        /// <summary>Decodes a server message by name (resolved from its id through the handshake's table).</summary>
        public static Result<IContractMessage> DecodeServer(IStateCodec codec, string name, byte[] body)
        {
            switch (name)
            {
                case "welcome":
                {
                    var decoded = WelcomeMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "dump":
                {
                    var decoded = DumpMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "echoed":
                {
                    var decoded = EchoedMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                default:
                    return Result<IContractMessage>.Fail(ErrorCodes.DecodeFailed, "no server message named " + name);
            }
        }

        /// <summary>Decodes a client message by name (resolved from its id through the handshake's table).</summary>
        public static Result<IContractMessage> DecodeClient(IStateCodec codec, string name, byte[] body)
        {
            switch (name)
            {
                case "move":
                {
                    var decoded = MoveMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "setName":
                {
                    var decoded = SetNameMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "addTag":
                {
                    var decoded = AddTagMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "bump":
                {
                    var decoded = BumpMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "requestDump":
                {
                    var decoded = RequestDumpMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "echo":
                {
                    var decoded = EchoMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "kickMe":
                {
                    var decoded = KickMeMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "dropMe":
                {
                    var decoded = DropMeMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                default:
                    return Result<IContractMessage>.Fail(ErrorCodes.DecodeFailed, "no client message named " + name);
            }
        }
    }

    /// <summary>Contract <c>optionsContract</c>.</summary>
    public static class OptionsContract
    {
        /// <summary>
        /// The contract hash this client was built against: sent in JOIN and
        /// compared with the handshake's. Message ids are not generated: they
        /// come from the handshake and are resolved by name.
        /// </summary>
        public const string Hash = "848cac5c";

        /// <summary>Client → server messages, by name.</summary>
        public static readonly IReadOnlyDictionary<string, MessageDef> ClientMessages = new Dictionary<string, MessageDef>
        {
        };

        /// <summary>Server → client messages, by name.</summary>
        public static readonly IReadOnlyDictionary<string, MessageDef> ServerMessages = new Dictionary<string, MessageDef>
        {
        };

        /// <summary>Decodes a server message by name (resolved from its id through the handshake's table).</summary>
        public static Result<IContractMessage> DecodeServer(IStateCodec codec, string name, byte[] body)
        {
            switch (name)
            {
                default:
                    return Result<IContractMessage>.Fail(ErrorCodes.DecodeFailed, "no server message named " + name);
            }
        }

        /// <summary>Decodes a client message by name (resolved from its id through the handshake's table).</summary>
        public static Result<IContractMessage> DecodeClient(IStateCodec codec, string name, byte[] body)
        {
            switch (name)
            {
                default:
                    return Result<IContractMessage>.Fail(ErrorCodes.DecodeFailed, "no client message named " + name);
            }
        }

        /// <summary>
        /// Join options for <c>JoinAsync</c> and <c>JoinByIdAsync</c> (typed
        /// options, PROTOCOL.md §6.2.1).
        /// </summary>
        public static TypedOptions JoinOptions(OptionsJoinMessage join) => new TypedOptions(join, null);

        /// <summary>
        /// Options for <c>CreateAsync</c> and <c>JoinOrCreateAsync</c>: the
        /// create options for a room the join creates, and the join options.
        /// </summary>
        public static TypedOptions CreateOptions(OptionsCreateMessage create, OptionsJoinMessage join) => new TypedOptions(join, create);
    }
}
