// <auto-generated>
// Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
// Do not edit: regenerate instead.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Bungohan.Protocol;

namespace Bungohan.Interop
{
    /// <summary>Contract message <c>addTag</c>.</summary>
    public sealed partial class AddTagMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "addTag";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("tag", FieldType.String));

        /// <summary><c>tag</c>: <c>string</c>.</summary>
        public string Tag { get; set; } = "";

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["tag"] = Tag;
            return payload;
        }

        public static AddTagMessage FromPayload(MsgMap payload)
        {
            var message = new AddTagMessage();
            message.Tag = (payload["tag"] as string ?? "");
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<AddTagMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<AddTagMessage>.Ok(FromPayload(decoded.Value)) : Result<AddTagMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>bump</c>.</summary>
    public sealed partial class BumpMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "bump";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("by", FieldType.Int32),
            new MessageField("alive", FieldType.Bool),
            new MessageField("note", FieldType.OptionalOf(FieldType.String)));

        /// <summary><c>by</c>: <c>int32</c>.</summary>
        public int By { get; set; }

        /// <summary><c>alive</c>: <c>bool</c>.</summary>
        public bool Alive { get; set; }

        /// <summary><c>note</c>: <c>optional&lt;string&gt;</c>.</summary>
        public string? Note { get; set; }

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["by"] = By;
            payload["alive"] = Alive;
            if (Note != null) payload["note"] = Note;
            return payload;
        }

        public static BumpMessage FromPayload(MsgMap payload)
        {
            var message = new BumpMessage();
            message.By = (int)Payloads.ToLong(payload["by"]);
            message.Alive = (payload["alive"] is true);
            message.Note = payload.TryGetValue("note", out object? v2) && v2 != null
                ? (string?)(v2 as string ?? "")
                : null;
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<BumpMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<BumpMessage>.Ok(FromPayload(decoded.Value)) : Result<BumpMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>dropMe</c>.</summary>
    public sealed partial class DropMeMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "dropMe";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName);

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            return payload;
        }

        public static DropMeMessage FromPayload(MsgMap payload)
        {
            var message = new DropMeMessage();
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<DropMeMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<DropMeMessage>.Ok(FromPayload(decoded.Value)) : Result<DropMeMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>dump</c>.</summary>
    public sealed partial class DumpMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "dump";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("turn", FieldType.UInt32),
            new MessageField("label", FieldType.String),
            new MessageField("log", FieldType.ArrayOf(FieldType.String)),
            new MessageField("players", FieldType.ArrayOf(FieldType.NestedOf(PlayerDumpMessage.Definition))));

        /// <summary><c>turn</c>: <c>uint32</c>.</summary>
        public uint Turn { get; set; }

        /// <summary><c>label</c>: <c>string</c>.</summary>
        public string Label { get; set; } = "";

        /// <summary><c>log</c>: <c>array&lt;string&gt;</c>.</summary>
        public List<string> Log { get; set; } = new List<string>();

        /// <summary><c>players</c>: <c>array&lt;nested&lt;playerDump&gt;&gt;</c>.</summary>
        public List<PlayerDumpMessage> Players { get; set; } = new List<PlayerDumpMessage>();

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["turn"] = Turn;
            payload["label"] = Label;
            payload["log"] = Payloads.FromList(Log, x0 => (object?)x0);
            payload["players"] = Payloads.FromList(Players, x0 => (object?)x0.ToPayload());
            return payload;
        }

        public static DumpMessage FromPayload(MsgMap payload)
        {
            var message = new DumpMessage();
            message.Turn = (uint)Payloads.ToLong(payload["turn"]);
            message.Label = (payload["label"] as string ?? "");
            message.Log = Payloads.ToList<string>(payload["log"], x0 => (x0 as string ?? ""));
            message.Players = Payloads.ToList<PlayerDumpMessage>(payload["players"], x0 => PlayerDumpMessage.FromPayload(Payloads.AsMap(x0)));
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<DumpMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<DumpMessage>.Ok(FromPayload(decoded.Value)) : Result<DumpMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>echo</c>.</summary>
    public sealed partial class EchoMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "echo";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("text", FieldType.String),
            new MessageField("count", FieldType.Int32));

        /// <summary><c>text</c>: <c>string</c>.</summary>
        public string Text { get; set; } = "";

        /// <summary><c>count</c>: <c>int32</c>.</summary>
        public int Count { get; set; }

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["text"] = Text;
            payload["count"] = Count;
            return payload;
        }

        public static EchoMessage FromPayload(MsgMap payload)
        {
            var message = new EchoMessage();
            message.Text = (payload["text"] as string ?? "");
            message.Count = (int)Payloads.ToLong(payload["count"]);
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<EchoMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<EchoMessage>.Ok(FromPayload(decoded.Value)) : Result<EchoMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>echoed</c>.</summary>
    public sealed partial class EchoedMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "echoed";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("text", FieldType.String),
            new MessageField("count", FieldType.Int32),
            new MessageField("note", FieldType.OptionalOf(FieldType.String)));

        /// <summary><c>text</c>: <c>string</c>.</summary>
        public string Text { get; set; } = "";

        /// <summary><c>count</c>: <c>int32</c>.</summary>
        public int Count { get; set; }

        /// <summary><c>note</c>: <c>optional&lt;string&gt;</c>.</summary>
        public string? Note { get; set; }

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["text"] = Text;
            payload["count"] = Count;
            if (Note != null) payload["note"] = Note;
            return payload;
        }

        public static EchoedMessage FromPayload(MsgMap payload)
        {
            var message = new EchoedMessage();
            message.Text = (payload["text"] as string ?? "");
            message.Count = (int)Payloads.ToLong(payload["count"]);
            message.Note = payload.TryGetValue("note", out object? v2) && v2 != null
                ? (string?)(v2 as string ?? "")
                : null;
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<EchoedMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<EchoedMessage>.Ok(FromPayload(decoded.Value)) : Result<EchoedMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>kickMe</c>.</summary>
    public sealed partial class KickMeMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "kickMe";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("reason", FieldType.String));

        /// <summary><c>reason</c>: <c>string</c>.</summary>
        public string Reason { get; set; } = "";

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["reason"] = Reason;
            return payload;
        }

        public static KickMeMessage FromPayload(MsgMap payload)
        {
            var message = new KickMeMessage();
            message.Reason = (payload["reason"] as string ?? "");
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<KickMeMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<KickMeMessage>.Ok(FromPayload(decoded.Value)) : Result<KickMeMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>move</c>.</summary>
    public sealed partial class MoveMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "move";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("dx", FieldType.Fixed(2)),
            new MessageField("dy", FieldType.Fixed(2)));

        /// <summary><c>dx</c>: <c>fixed:2</c>.</summary>
        public double Dx { get; set; }

        /// <summary><c>dy</c>: <c>fixed:2</c>.</summary>
        public double Dy { get; set; }

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["dx"] = Dx;
            payload["dy"] = Dy;
            return payload;
        }

        public static MoveMessage FromPayload(MsgMap payload)
        {
            var message = new MoveMessage();
            message.Dx = Payloads.ToDouble(payload["dx"]);
            message.Dy = Payloads.ToDouble(payload["dy"]);
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<MoveMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<MoveMessage>.Ok(FromPayload(decoded.Value)) : Result<MoveMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>playerDump</c>.</summary>
    public sealed partial class PlayerDumpMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "playerDump";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("id", FieldType.String),
            new MessageField("name", FieldType.String),
            new MessageField("x", FieldType.Fixed(2)),
            new MessageField("y", FieldType.Fixed(2)),
            new MessageField("score", FieldType.Int32),
            new MessageField("alive", FieldType.Bool),
            new MessageField("tags", FieldType.ArrayOf(FieldType.String)));

        /// <summary><c>id</c>: <c>string</c>.</summary>
        public string Id { get; set; } = "";

        /// <summary><c>name</c>: <c>string</c>.</summary>
        public string Name { get; set; } = "";

        /// <summary><c>x</c>: <c>fixed:2</c>.</summary>
        public double X { get; set; }

        /// <summary><c>y</c>: <c>fixed:2</c>.</summary>
        public double Y { get; set; }

        /// <summary><c>score</c>: <c>int32</c>.</summary>
        public int Score { get; set; }

        /// <summary><c>alive</c>: <c>bool</c>.</summary>
        public bool Alive { get; set; }

        /// <summary><c>tags</c>: <c>array&lt;string&gt;</c>.</summary>
        public List<string> Tags { get; set; } = new List<string>();

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["id"] = Id;
            payload["name"] = Name;
            payload["x"] = X;
            payload["y"] = Y;
            payload["score"] = Score;
            payload["alive"] = Alive;
            payload["tags"] = Payloads.FromList(Tags, x0 => (object?)x0);
            return payload;
        }

        public static PlayerDumpMessage FromPayload(MsgMap payload)
        {
            var message = new PlayerDumpMessage();
            message.Id = (payload["id"] as string ?? "");
            message.Name = (payload["name"] as string ?? "");
            message.X = Payloads.ToDouble(payload["x"]);
            message.Y = Payloads.ToDouble(payload["y"]);
            message.Score = (int)Payloads.ToLong(payload["score"]);
            message.Alive = (payload["alive"] is true);
            message.Tags = Payloads.ToList<string>(payload["tags"], x0 => (x0 as string ?? ""));
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<PlayerDumpMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<PlayerDumpMessage>.Ok(FromPayload(decoded.Value)) : Result<PlayerDumpMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>requestDump</c>.</summary>
    public sealed partial class RequestDumpMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "requestDump";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName);

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            return payload;
        }

        public static RequestDumpMessage FromPayload(MsgMap payload)
        {
            var message = new RequestDumpMessage();
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<RequestDumpMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<RequestDumpMessage>.Ok(FromPayload(decoded.Value)) : Result<RequestDumpMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>setName</c>.</summary>
    public sealed partial class SetNameMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "setName";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("name", FieldType.String));

        /// <summary><c>name</c>: <c>string</c>.</summary>
        public string Name { get; set; } = "";

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["name"] = Name;
            return payload;
        }

        public static SetNameMessage FromPayload(MsgMap payload)
        {
            var message = new SetNameMessage();
            message.Name = (payload["name"] as string ?? "");
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<SetNameMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<SetNameMessage>.Ok(FromPayload(decoded.Value)) : Result<SetNameMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>welcome</c>.</summary>
    public sealed partial class WelcomeMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "welcome";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("sessionId", FieldType.String),
            new MessageField("players", FieldType.UInt8));

        /// <summary><c>sessionId</c>: <c>string</c>.</summary>
        public string SessionId { get; set; } = "";

        /// <summary><c>players</c>: <c>uint8</c>.</summary>
        public byte Players { get; set; }

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["sessionId"] = SessionId;
            payload["players"] = Players;
            return payload;
        }

        public static WelcomeMessage FromPayload(MsgMap payload)
        {
            var message = new WelcomeMessage();
            message.SessionId = (payload["sessionId"] as string ?? "");
            message.Players = (byte)Payloads.ToLong(payload["players"]);
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<WelcomeMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<WelcomeMessage>.Ok(FromPayload(decoded.Value)) : Result<WelcomeMessage>.Fail(decoded.Error!);
        }
    }
}
