// <auto-generated>
// Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
// Do not edit: regenerate instead.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Bungohan.Protocol;

namespace Bungohan.Interop
{
    /// <summary>Schema class <c>Interop.Player</c>.</summary>
    public sealed partial class Interop_Player : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "Interop.Player";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new Interop_Player(),
            new SchemaField("name", "string"),
            new SchemaField("x", "fixed:2"),
            new SchemaField("y", "fixed:2"),
            new SchemaField("score", "int32"),
            new SchemaField("alive", "bool"),
            new SchemaField("tags", "set<string>"));

        public override SchemaClass Class => Definition;

        private string _name = "";

        /// <summary><c>name</c>: <c>string</c>.</summary>
        public string Name => _name;

        /// <summary>Name changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? NameChanged;

        private double _x;

        /// <summary><c>x</c>: <c>fixed:2</c>.</summary>
        public double X => _x;

        /// <summary>X changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? XChanged;

        private double _y;

        /// <summary><c>y</c>: <c>fixed:2</c>.</summary>
        public double Y => _y;

        /// <summary>Y changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? YChanged;

        private int _score;

        /// <summary><c>score</c>: <c>int32</c>.</summary>
        public int Score => _score;

        /// <summary>Score changed: (value, previous), after the frame is applied.</summary>
        public event Action<int, int>? ScoreChanged;

        private bool _alive;

        /// <summary><c>alive</c>: <c>bool</c>.</summary>
        public bool Alive => _alive;

        /// <summary>Alive changed: (value, previous), after the frame is applied.</summary>
        public event Action<bool, bool>? AliveChanged;

        /// <summary><c>tags</c>: <c>set&lt;string&gt;</c>.</summary>
        public SetSchema<string> Tags { get; } = new SetSchema<string>("set<string>");

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            0 => Apply(0, ref _name, wire, changes, NameChanged),
            1 => Apply(1, ref _x, wire, changes, XChanged),
            2 => Apply(2, ref _y, wire, changes, YChanged),
            3 => Apply(3, ref _score, wire, changes, ScoreChanged),
            4 => Apply(4, ref _alive, wire, changes, AliveChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            5 => Tags,
            _ => null,
        };
    }

    /// <summary>Schema class <c>Interop.State</c>.</summary>
    public sealed partial class Interop_State : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "Interop.State";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new Interop_State(),
            new SchemaField("turn", "uint32"),
            new SchemaField("label", "string"),
            new SchemaField("players", "schemaMap<string,Interop.Player>"),
            new SchemaField("log", "array<string>"));

        public override SchemaClass Class => Definition;

        private uint _turn;

        /// <summary><c>turn</c>: <c>uint32</c>.</summary>
        public uint Turn => _turn;

        /// <summary>Turn changed: (value, previous), after the frame is applied.</summary>
        public event Action<uint, uint>? TurnChanged;

        private string _label = "";

        /// <summary><c>label</c>: <c>string</c>.</summary>
        public string Label => _label;

        /// <summary>Label changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? LabelChanged;

        /// <summary><c>players</c>: <c>schemaMap&lt;string,Interop.Player&gt;</c>.</summary>
        public MapSchema<string, Interop_Player> Players { get; } = new MapSchema<string, Interop_Player>("schemaMap<string,Interop.Player>");

        /// <summary><c>log</c>: <c>array&lt;string&gt;</c>.</summary>
        public ArraySchema<string> Log { get; } = new ArraySchema<string>("array<string>");

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            0 => Apply(0, ref _turn, wire, changes, TurnChanged),
            1 => Apply(1, ref _label, wire, changes, LabelChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            2 => Players,
            3 => Log,
            _ => null,
        };
    }

    /// <summary>Every generated schema class.</summary>
    public static class Schemas
    {
        /// <summary>Registers every class, so the replica can instantiate what the server sends.</summary>
        public static SchemaRegistry Register(SchemaRegistry registry)
        {
            registry.Register(Interop_Player.Definition);
            registry.Register(Interop_State.Definition);
            return registry;
        }

        public static SchemaRegistry CreateRegistry() => Register(new SchemaRegistry());
    }
}
