# Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Everything generated, preloaded:
##
##     const Bindings = preload("res://…/bindings.gd")
##     var registry = Bindings.create_registry()

const SchemaRegistry = preload("res://addons/bungohan/replica/schema_registry.gd")

const Bullet = preload("schemas/bullet.gd")
const Enemy = preload("schemas/enemy.gd")
const GameState = preload("schemas/game_state.gd")
const LobbyState = preload("schemas/lobby_state.gd")
const Loot = preload("schemas/loot.gd")
const Player = preload("schemas/player.gd")
const RoomInfo = preload("schemas/room_info.gd")
const ErrorMessage = preload("messages/error_message.gd")
const GameEndedMessage = preload("messages/game_ended_message.gd")
const GameResultMessage = preload("messages/game_result_message.gd")
const GameStartedMessage = preload("messages/game_started_message.gd")
const InputMessage = preload("messages/input_message.gd")
const JoinByCodeMessage = preload("messages/join_by_code_message.gd")
const PlayerJoinedMessage = preload("messages/player_joined_message.gd")
const PlayerLeftMessage = preload("messages/player_left_message.gd")
const ReadyMessage = preload("messages/ready_message.gd")
const RefreshRoomsMessage = preload("messages/refresh_rooms_message.gd")
const RoomFoundMessage = preload("messages/room_found_message.gd")
const ShooterCreateOptionsMessage = preload("messages/shooter_create_options_message.gd")
const ShooterJoinOptionsMessage = preload("messages/shooter_join_options_message.gd")
const StartGameMessage = preload("messages/start_game_message.gd")
const LobbyContract = preload("contracts/lobby_contract.gd")
const ShooterContract = preload("contracts/shooter_contract.gd")

## Every schema class.
const SCHEMAS := [Bullet, Enemy, GameState, LobbyState, Loot, Player, RoomInfo]


## A registry holding every schema class, so the replica can instantiate
## what the server sends.
static func create_registry():
	var registry = SchemaRegistry.new()
	for schema in SCHEMAS:
		registry.register(schema)
	return registry
