/**
 * `--lang csharp`: bindings for the Bungohan.Protocol core
 * (clients/csharp), for Unity and Godot .NET: netstandard2.1, C# 9.
 *
 * - `Schemas.cs`: a class per schema, each primitive field a read-only
 *   property with a `…Changed(value, previous)` event, nested instances and
 *   collections as read-only properties; `Schemas.CreateRegistry()`.
 * - `Messages.cs`: a class per contract message, with `Definition`,
 *   `ToPayload`/`FromPayload` and `Encode`/`Decode` for a codec.
 * - `Contracts.cs`: a static class per contract: its `Hash`, and its
 *   messages by name. Numeric ids are never generated: they come from the
 *   join handshake and are resolved by name (spec §4.2).
 */
import {
  type EnumValue,
  type Field,
  type MessageDef,
  PROTOCOL_VERSION,
  parseFieldType,
} from "@bungohan/types"
import type { CodegenModel, SchemaModel } from "./model"
import { CodegenError } from "./model"
import { claim, pascal } from "./names"

export interface CSharpOptions {
  /** Namespace of the generated code. */
  readonly namespace: string
  /** Shown in the header comment (module names, never absolute paths). */
  readonly source: string
}

const SCALARS: Readonly<Record<string, string>> = {
  int8: "sbyte",
  int16: "short",
  int32: "int",
  uint8: "byte",
  uint16: "ushort",
  uint32: "uint",
  float32: "float",
  float64: "double",
  string: "string",
  bool: "bool",
}

function scalar(type: string): string {
  if (type.startsWith("fixed:")) return "double"
  const out = SCALARS[type]
  if (out === undefined) throw new CodegenError(`no C# type for ${type}`)
  return out
}

function literal(value: string): string {
  return JSON.stringify(value)
}

function header(options: CSharpOptions): string[] {
  return [
    "// <auto-generated>",
    `// Generated by @bungohan/codegen from ${options.source} (${PROTOCOL_VERSION}).`,
    "// Do not edit: regenerate instead.",
    "// </auto-generated>",
    "#nullable enable",
    "using System;",
    "using System.Collections.Generic;",
    "using Bungohan.Protocol;",
    "",
    `namespace ${options.namespace}`,
    "{",
  ]
}

/** Indents every non-empty line by `levels` × 4 spaces. */
function indent(lines: readonly string[], levels = 1): string[] {
  const pad = "    ".repeat(levels)
  return lines.map((line) => (line === "" ? "" : pad + line))
}

function file(options: CSharpOptions, blocks: string[][]): string {
  const body: string[] = []
  blocks.forEach((block, i) => {
    if (i > 0) body.push("")
    body.push(...indent(block))
  })
  return `${[...header(options), ...body, "}"].join("\n")}\n`
}

// ===========================================================================
// Schemas
// ===========================================================================

const SCHEMA_RESERVED = [
  "Class",
  "Definition",
  "SchemaName",
  "ApplyField",
  "GetChild",
  "Apply",
  "Equals",
  "GetHashCode",
  "ToString",
  "GetType",
  "MemberwiseClone",
  "Finalize",
  "ReferenceEquals",
]

function schemaClass(
  schema: SchemaModel,
  className: (name: string) => string,
): string[] {
  const cls = className(schema.name)
  const taken = new Set([cls, ...SCHEMA_RESERVED])
  const members = schema.fields.map((field) => claim(pascal(field.name), taken))
  const lines: string[] = [
    `/// <summary>Schema class <c>${escapeXml(schema.name)}</c>.</summary>`,
    `public sealed partial class ${cls} : Schema`,
    "{",
    `    /// <summary>The class's name on the wire.</summary>`,
    `    public const string SchemaName = ${literal(schema.name)};`,
    "",
    "    /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>",
    `    public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new ${cls}()${schema.fields.length > 0 ? "," : ");"}`,
  ]
  schema.fields.forEach((field, i) => {
    const last = i === schema.fields.length - 1
    lines.push(
      `        new SchemaField(${literal(field.name)}, ${literal(field.type)})${last ? ");" : ","}`,
    )
  })
  lines.push("", "    public override SchemaClass Class => Definition;")

  const applies: string[] = []
  const children: string[] = []
  schema.fields.forEach((field, i) => {
    const member = members[i] ?? ""
    const parsed = parseFieldType(field.type)
    if (parsed === undefined) {
      throw new CodegenError(
        `${schema.name}.${field.name}: bad type ${field.type}`,
      )
    }
    const doc = `/// <summary><c>${escapeXml(field.name)}</c>: <c>${escapeXml(field.type)}</c>.</summary>`
    lines.push("")
    if (parsed.kind === "primitive" || parsed.kind === "int") {
      const type = scalar(parsed.type)
      const backing = `_${member.charAt(0).toLowerCase()}${member.slice(1)}`
      const event = claim(`${member}Changed`, taken)
      const zero = type === "string" ? ' = ""' : ""
      lines.push(
        `    private ${type} ${backing}${zero};`,
        "",
        `    ${doc}`,
        `    public ${type} ${member} => ${backing};`,
        "",
        `    /// <summary>${member} changed: (value, previous), after the frame is applied.</summary>`,
        `    public event Action<${type}, ${type}>? ${event};`,
      )
      applies.push(
        `${i} => Apply(${i}, ref ${backing}, wire, changes, ${event}),`,
      )
      return
    }
    let type: string
    switch (parsed.kind) {
      case "schema":
        type = className(parsed.schema)
        break
      case "map":
        type = `MapSchema<${scalar(parsed.key)}, ${scalar(parsed.element)}>`
        break
      case "set":
        type = `SetSchema<${scalar(parsed.element)}>`
        break
      case "array":
        type = `ArraySchema<${scalar(parsed.element)}>`
        break
      case "schemaMap":
        type = `MapSchema<${scalar(parsed.key)}, ${className(parsed.schema)}>`
        break
      case "schemaSet":
        type = `SetSchema<${className(parsed.schema)}>`
        break
      default:
        type = `ArraySchema<${className(parsed.schema)}>`
    }
    const init =
      parsed.kind === "schema"
        ? `new ${type}()`
        : `new ${type}(${literal(field.type)})`
    lines.push(`    ${doc}`, `    public ${type} ${member} { get; } = ${init};`)
    children.push(`${i} => ${member},`)
  })

  lines.push(
    "",
    "    protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch",
    "    {",
    ...applies.map((line) => `        ${line}`),
    "        _ => false,",
    "    };",
    "",
    "    protected override object? GetChild(int index) => index switch",
    "    {",
    ...children.map((line) => `        ${line}`),
    "        _ => null,",
    "    };",
    "}",
  )
  return lines
}

function registry(model: CodegenModel, className: (name: string) => string) {
  return [
    "/// <summary>Every generated schema class.</summary>",
    "public static class Schemas",
    "{",
    "    /// <summary>Registers every class, so the replica can instantiate what the server sends.</summary>",
    "    public static SchemaRegistry Register(SchemaRegistry registry)",
    "    {",
    ...model.schemas.map(
      (schema) =>
        `        registry.Register(${className(schema.name)}.Definition);`,
    ),
    "        return registry;",
    "    }",
    "",
    "    public static SchemaRegistry CreateRegistry() => Register(new SchemaRegistry());",
    "}",
  ]
}

// ===========================================================================
// Messages
// ===========================================================================

const MESSAGE_RESERVED = [
  "MessageName",
  "Definition",
  "MessageDefinition",
  "ToPayload",
  "FromPayload",
  "Encode",
  "Decode",
  "Equals",
  "GetHashCode",
  "ToString",
  "GetType",
  "MemberwiseClone",
  "Finalize",
  "ReferenceEquals",
]

/** A C# enum generated for a string enum field. */
interface EnumPlan {
  readonly type: string
  readonly valuesField: string
  readonly members: readonly string[]
  readonly values: readonly EnumValue[]
}

function enumOf(field: Field): Extract<Field, { kind: "enum" }> | undefined {
  switch (field.kind) {
    case "enum":
      return field
    case "array":
    case "map":
    case "optional":
      return enumOf(field.of)
    default:
      return undefined
  }
}

/** The layout grammar of spec §6.7.4, for doc comments. */
export function typeText(field: Field): string {
  switch (field.kind) {
    case "fixed":
      return `fixed:${field.decimals}`
    case "enum":
      return `enum[${field.values.map((v) => JSON.stringify(v)).join("|")}]`
    case "array":
    case "map":
    case "optional":
      return `${field.kind}<${typeText(field.of)}>`
    case "nested":
      return `nested<${field.message.name}>`
    default:
      return field.kind
  }
}

function escapeXml(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

class MessageEmitter {
  private readonly _enums = new Map<Field, EnumPlan>()
  private readonly _taken: Set<string>

  public constructor(
    private readonly def: MessageDef,
    private readonly className: (def: MessageDef) => string,
  ) {
    this._taken = new Set([className(def), ...MESSAGE_RESERVED])
  }

  public emit(): string[] {
    const def = this.def
    const cls = this.className(def)
    const names = def.fieldNames.map((name) => claim(pascal(name), this._taken))
    const lines: string[] = []
    const fieldLines: string[] = []
    def.fieldNames.forEach((name, i) => {
      const field = def.fields[name]
      if (field === undefined) return
      const member = names[i] ?? ""
      this._planEnum(field, member)
      const optional = field.kind === "optional"
      const type = optional ? `${this._type(field.of)}?` : this._type(field)
      const init = optional ? "" : this._default(field)
      fieldLines.push(
        "",
        `    /// <summary><c>${escapeXml(name)}</c>: <c>${escapeXml(typeText(field))}</c>.</summary>`,
        `    public ${type} ${member} { get; set; }${init === "" ? "" : ` = ${init};`}`,
      )
    })

    lines.push(
      `/// <summary>Contract message <c>${escapeXml(def.name)}</c>.</summary>`,
      `public sealed partial class ${cls} : IContractMessage`,
      "{",
      "    /// <summary>The message's name on the wire; its id comes from the handshake.</summary>",
      `    public const string MessageName = ${literal(def.name)};`,
      "",
      "    /// <summary>The declaration the codecs encode with.</summary>",
      `    public static readonly MessageDef Definition = new MessageDef(MessageName${def.fieldNames.length > 0 ? "," : ");"}`,
    )
    def.fieldNames.forEach((name, i) => {
      const field = def.fields[name]
      if (field === undefined) return
      const last = i === def.fieldNames.length - 1
      lines.push(
        `        new MessageField(${literal(name)}, ${this._fieldType(field)})${last ? ");" : ","}`,
      )
    })
    for (const plan of this._enums.values()) {
      lines.push(
        "",
        `    /// <summary>The values of <see cref="${plan.type}"/>, in index order.</summary>`,
        `    private static readonly object[] ${plan.valuesField} = { ${plan.values.map((v) => (typeof v === "string" ? literal(v) : String(v))).join(", ")} };`,
        "",
        `    public enum ${plan.type}`,
        "    {",
        ...plan.members.flatMap((member, i) => [
          `        /// <summary><c>${escapeXml(JSON.stringify(plan.values[i]))}</c></summary>`,
          `        ${member} = ${i},`,
        ]),
        "    }",
      )
    }
    lines.push(...fieldLines)

    lines.push(
      "",
      "    MessageDef IContractMessage.MessageDefinition => Definition;",
      "",
      "    public MsgMap ToPayload()",
      "    {",
      "        var payload = new MsgMap();",
    )
    def.fieldNames.forEach((name, i) => {
      const field = def.fields[name]
      if (field === undefined) return
      const member = names[i] ?? ""
      if (field.kind === "optional") {
        const value = this._isValueType(field.of) ? `${member}.Value` : member
        lines.push(
          `        if (${member} != null) payload[${literal(name)}] = ${this._to(field.of, value, 0)};`,
        )
      } else {
        lines.push(
          `        payload[${literal(name)}] = ${this._to(field, member, 0)};`,
        )
      }
    })
    lines.push(
      "        return payload;",
      "    }",
      "",
      `    public static ${cls} FromPayload(MsgMap payload)`,
      "    {",
      `        var message = new ${cls}();`,
    )
    def.fieldNames.forEach((name, i) => {
      const field = def.fields[name]
      if (field === undefined) return
      const member = names[i] ?? ""
      if (field.kind === "optional") {
        const v = `v${i}`
        lines.push(
          `        message.${member} = payload.TryGetValue(${literal(name)}, out object? ${v}) && ${v} != null`,
          `            ? (${this._type(field.of)}?)${this._from(field.of, v, 0)}`,
          "            : null;",
        )
      } else {
        lines.push(
          `        message.${member} = ${this._from(field, `payload[${literal(name)}]`, 0)};`,
        )
      }
    })
    lines.push(
      "        return message;",
      "    }",
      "",
      "    /// <summary>Encodes with the room's codec.</summary>",
      "    public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());",
      "",
      "    /// <summary>Decodes a body with the room's codec.</summary>",
      `    public static Result<${cls}> Decode(IStateCodec codec, byte[] body)`,
      "    {",
      "        Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);",
      `        return decoded.IsOk ? Result<${cls}>.Ok(FromPayload(decoded.Value)) : Result<${cls}>.Fail(decoded.Error!);`,
      "    }",
      "}",
    )
    return lines
  }

  private _planEnum(field: Field, member: string): void {
    const found = enumOf(field)
    if (found === undefined) return
    const values = found.values
    if (!values.every((v) => typeof v === "string")) return
    const taken = new Set<string>()
    const members = values.map((v) => pascal(v))
    const unique = members.every((m) => !taken.has(m) && taken.add(m))
    if (!unique) return
    this._enums.set(found, {
      type: claim(`${member}Value`, this._taken),
      valuesField: claim(
        `s_${member.charAt(0).toLowerCase()}${member.slice(1)}Values`,
        this._taken,
      ),
      members,
      values,
    })
  }

  private _isValueType(field: Field): boolean {
    switch (field.kind) {
      case "string":
      case "array":
      case "map":
      case "optional":
      case "nested":
        return false
      case "enum":
        return (
          this._enums.has(field) ||
          field.values.every((v) => typeof v === "number")
        )
      default:
        return true
    }
  }

  private _type(field: Field): string {
    switch (field.kind) {
      case "fixed":
        return "double"
      case "enum": {
        const plan = this._enums.get(field)
        if (plan !== undefined) return plan.type
        if (field.values.every((v) => typeof v === "number")) return "double"
        if (field.values.every((v) => typeof v === "string")) return "string"
        return "object"
      }
      case "array":
        return `List<${this._type(field.of)}>`
      case "map":
        return `Dictionary<string, ${this._type(field.of)}>`
      case "optional":
        return `${this._type(field.of)}?`
      case "nested":
        return this.className(field.message)
      default:
        return scalar(field.kind)
    }
  }

  private _default(field: Field): string {
    switch (field.kind) {
      case "string":
        return '""'
      case "array":
      case "map":
      case "nested":
        return `new ${this._type(field)}()`
      case "enum": {
        const type = this._type(field)
        if (type === "string" || type === "object") {
          return literal(String(field.values[0] ?? ""))
        }
        return ""
      }
      default:
        return ""
    }
  }

  /** The Bungohan.Protocol FieldType expression of a field. */
  private _fieldType(field: Field): string {
    switch (field.kind) {
      case "fixed":
        return `FieldType.Fixed(${field.decimals})`
      case "enum":
        return `FieldType.Enum(${field.values.map((v) => (typeof v === "string" ? literal(v) : `${v}d`)).join(", ")})`
      case "array":
        return `FieldType.ArrayOf(${this._fieldType(field.of)})`
      case "map":
        return `FieldType.MapOf(${this._fieldType(field.of)})`
      case "optional":
        return `FieldType.OptionalOf(${this._fieldType(field.of)})`
      case "nested":
        return `FieldType.NestedOf(${this.className(field.message)}.Definition)`
      default:
        return `FieldType.${pascal(field.kind).replace("Uint", "UInt")}`
    }
  }

  /** Member value → payload value (object?). */
  private _to(field: Field, expr: string, depth: number): string {
    const x = `x${depth}`
    switch (field.kind) {
      case "enum": {
        const plan = this._enums.get(field)
        return plan === undefined ? expr : `${plan.valuesField}[(int)${expr}]`
      }
      case "array":
        return `Payloads.FromList(${expr}, ${x} => (object?)${this._to(field.of, x, depth + 1)})`
      case "map":
        return `Payloads.FromMap(${expr}, ${x} => (object?)${this._to(field.of, x, depth + 1)})`
      case "optional":
        return this._isValueType(field.of)
          ? `(${expr}.HasValue ? (object?)${this._to(field.of, `${expr}.Value`, depth)} : null)`
          : `(${expr} == null ? null : (object?)${this._to(field.of, expr, depth)})`
      case "nested":
        return `${expr}.ToPayload()`
      default:
        return expr
    }
  }

  /** Payload value (object?) → member value. */
  private _from(field: Field, expr: string, depth: number): string {
    const x = `x${depth}`
    switch (field.kind) {
      case "int8":
      case "int16":
      case "int32":
      case "uint8":
      case "uint16":
      case "uint32":
        return `(${scalar(field.kind)})Payloads.ToLong(${expr})`
      case "float32":
        return `(float)Payloads.ToDouble(${expr})`
      case "float64":
      case "fixed":
        return `Payloads.ToDouble(${expr})`
      case "string":
        return `(${expr} as string ?? "")`
      case "bool":
        return `(${expr} is true)`
      case "enum": {
        const plan = this._enums.get(field)
        if (plan !== undefined) {
          return `(${plan.type})Math.Max(0, Array.IndexOf(${plan.valuesField}, ${expr}))`
        }
        const type = this._type(field)
        if (type === "double") return `Payloads.ToDouble(${expr})`
        if (type === "string") return `(${expr} as string ?? "")`
        return `(${expr} ?? "")`
      }
      case "array":
        return `Payloads.ToList<${this._type(field.of)}>(${expr}, ${x} => ${this._from(field.of, x, depth + 1)})`
      case "map":
        return `Payloads.ToDictionary<${this._type(field.of)}>(${expr}, ${x} => ${this._from(field.of, x, depth + 1)})`
      case "optional":
        return `(${expr} == null ? (${this._type(field.of)}?)null : ${this._from(field.of, expr, depth)})`
      case "nested":
        return `${this.className(field.message)}.FromPayload(Payloads.AsMap(${expr}))`
    }
  }
}

// ===========================================================================
// Contracts
// ===========================================================================

function contractClass(
  contract: CodegenModel["contracts"][number],
  cls: string,
  messageClass: (def: MessageDef) => string,
): string[] {
  const table = (defs: readonly MessageDef[]): string[] =>
    defs.map(
      (def) =>
        `        [${literal(def.name)}] = ${messageClass(def)}.Definition,`,
    )
  const decoder = (side: string, defs: readonly MessageDef[]): string[] => [
    `    /// <summary>Decodes a ${side} message by name (resolved from its id through the handshake's table).</summary>`,
    `    public static Result<IContractMessage> Decode${side === "client" ? "Client" : "Server"}(IStateCodec codec, string name, byte[] body)`,
    "    {",
    "        switch (name)",
    "        {",
    ...defs.flatMap((def) => [
      `            case ${literal(def.name)}:`,
      "            {",
      `                var decoded = ${messageClass(def)}.Decode(codec, body);`,
      "                return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);",
      "            }",
    ]),
    "            default:",
    `                return Result<IContractMessage>.Fail(ErrorCodes.DecodeFailed, "no ${side} message named " + name);`,
    "        }",
    "    }",
  ]
  return [
    `/// <summary>Contract <c>${escapeXml(contract.name)}</c>.</summary>`,
    `public static class ${cls}`,
    "{",
    "    /// <summary>",
    "    /// The contract hash this client was built against: sent in JOIN and",
    "    /// compared with the handshake's. Message ids are not generated: they",
    "    /// come from the handshake and are resolved by name.",
    "    /// </summary>",
    `    public const string Hash = ${literal(contract.hash)};`,
    "",
    "    /// <summary>Client → server messages, by name.</summary>",
    "    public static readonly IReadOnlyDictionary<string, MessageDef> ClientMessages = new Dictionary<string, MessageDef>",
    "    {",
    ...table(contract.client),
    "    };",
    "",
    "    /// <summary>Server → client messages, by name.</summary>",
    "    public static readonly IReadOnlyDictionary<string, MessageDef> ServerMessages = new Dictionary<string, MessageDef>",
    "    {",
    ...table(contract.server),
    "    };",
    "",
    ...decoder("server", contract.server),
    "",
    ...decoder("client", contract.client),
    "}",
  ]
}

// ===========================================================================

export function generateCSharp(
  model: CodegenModel,
  options: CSharpOptions,
): Map<string, string> {
  // Type names are unique across the namespace.
  const types = new Set(["Schemas"])
  const schemaNames = new Map<string, string>()
  for (const schema of model.schemas) {
    schemaNames.set(schema.name, claim(pascal(schema.name), types))
  }
  const messageNames = new Map<string, string>()
  for (const def of model.messages) {
    messageNames.set(def.name, claim(`${pascal(def.name)}Message`, types))
  }
  const contractNames = new Map<string, string>()
  for (const contract of model.contracts) {
    contractNames.set(contract.name, claim(pascal(contract.name), types))
  }
  const className = (name: string): string => {
    const out = schemaNames.get(name)
    if (out === undefined)
      throw new CodegenError(`unknown schema class ${name}`)
    return out
  }
  const messageClass = (def: MessageDef): string => {
    const out = messageNames.get(def.name)
    if (out === undefined) throw new CodegenError(`unknown message ${def.name}`)
    return out
  }

  const files = new Map<string, string>()
  if (model.schemas.length > 0) {
    files.set(
      "Schemas.cs",
      file(options, [
        ...model.schemas.map((schema) => schemaClass(schema, className)),
        registry(model, className),
      ]),
    )
  }
  if (model.messages.length > 0) {
    files.set(
      "Messages.cs",
      file(
        options,
        model.messages.map((def) =>
          new MessageEmitter(def, messageClass).emit(),
        ),
      ),
    )
  }
  if (model.contracts.length > 0) {
    files.set(
      "Contracts.cs",
      file(
        options,
        model.contracts.map((contract) =>
          contractClass(
            contract,
            contractNames.get(contract.name) ?? "",
            messageClass,
          ),
        ),
      ),
    )
  }
  return files
}
