/**
 * `--lang gdscript`: bindings for the Bungohan Godot addon
 * (clients/godot/addons/bungohan). One script per class, no `class_name`
 * (so nothing collides with the project's own global classes); everything
 * is reached through `bindings.gd`:
 *
 * - `schemas/<name>.gd`: a schema class, a typed var per primitive field
 *   with a `<field>_changed(value, previous)` signal, nested instances and
 *   collections as vars.
 * - `messages/<name>_message.gd`: a contract message, with `definition()`,
 *   `to_payload()`/`from_payload()` and `encode()`/`decode()`.
 * - `contracts/<name>.gd`: a contract's `HASH` and its messages by name.
 *   Numeric ids are never generated (spec §4.2).
 * - `bindings.gd`: preloads everything; `create_registry()`.
 */
import {
  type Field,
  type MessageDef,
  PROTOCOL_VERSION,
  parseFieldType,
} from "@bungohan/types"
import { typeText } from "./csharp"
import type { CodegenModel, SchemaModel } from "./model"
import { CodegenError } from "./model"
import { claim, pascal, snake, upperSnake } from "./names"

export interface GDScriptOptions {
  /** Where the addon lives in the Godot project. */
  readonly addon: string
  /** Shown in the header comment (module names, never absolute paths). */
  readonly source: string
}

/** GDScript keywords and the members of Object/RefCounted. */
const RESERVED = new Set([
  "if",
  "elif",
  "else",
  "for",
  "while",
  "match",
  "when",
  "break",
  "continue",
  "pass",
  "return",
  "class",
  "class_name",
  "extends",
  "is",
  "in",
  "as",
  "self",
  "super",
  "signal",
  "func",
  "static",
  "const",
  "enum",
  "var",
  "breakpoint",
  "preload",
  "await",
  "yield",
  "assert",
  "void",
  "not",
  "and",
  "or",
  "true",
  "false",
  "null",
  "PI",
  "TAU",
  "INF",
  "NAN",
  "free",
  "get",
  "set",
  "get_class",
  "is_class",
  "get_script",
  "set_script",
  "script",
  "has_method",
  "call",
  "callv",
  "call_deferred",
  "connect",
  "disconnect",
  "emit_signal",
  "is_connected",
  "notification",
  "to_string",
  "get_instance_id",
  "get_property_list",
  "get_method_list",
  "has_signal",
  "get_signal_list",
  "set_meta",
  "get_meta",
  "has_meta",
  "remove_meta",
  "get_meta_list",
  "tr",
  "tr_n",
  "set_block_signals",
  "is_blocking_signals",
  "notify_property_list_changed",
  "property_can_revert",
  "property_get_revert",
  "set_deferred",
  "set_indexed",
  "get_indexed",
  "is_queued_for_deletion",
  "cancel_free",
  "add_user_signal",
  "has_user_signal",
  "remove_user_signal",
  "can_translate_messages",
  "set_message_translation",
  "get_signal_connection_list",
  "get_incoming_connections",
  "reference",
  "unreference",
  "init_ref",
  "get_reference_count",
  "get_rid",
])

function literal(value: string): string {
  return JSON.stringify(value)
}

function header(options: GDScriptOptions, extend: string): string[] {
  return [
    `# Generated by @bungohan/codegen from ${options.source} (${PROTOCOL_VERSION}).`,
    "# Do not edit: regenerate instead.",
    `extends ${extend}`,
  ]
}

function text(lines: readonly string[]): string {
  return `${lines.join("\n")}\n`
}

function scalar(type: string): { type: string; zero: string } {
  if (type === "string") return { type: "String", zero: '""' }
  if (type === "bool") return { type: "bool", zero: "false" }
  if (type === "float32" || type === "float64" || type.startsWith("fixed:")) {
    return { type: "float", zero: "0.0" }
  }
  return { type: "int", zero: "0" }
}

// ===========================================================================
// Schemas
// ===========================================================================

function schemaScript(
  schema: SchemaModel,
  options: GDScriptOptions,
  fileOf: (name: string) => string,
): string {
  const replica = `${options.addon}/replica`
  const taken = new Set([...RESERVED])
  const members = schema.fields.map((field) => claim(snake(field.name), taken))
  const consts = new Set(["SCHEMA_NAME", "FIELDS"])
  const preloads = new Map<string, string>() // const name → path
  const collectionConst = (kind: string): string => {
    const name =
      kind === "map"
        ? "MapSchema"
        : kind === "set"
          ? "SetSchema"
          : "ArraySchema"
    consts.add(name)
    preloads.set(name, `${replica}/${snake(name)}.gd`)
    return name
  }
  const nestedConst = new Map<string, string>()
  const classConst = (name: string): string => {
    let out = nestedConst.get(name)
    if (out === undefined) {
      out = claim(pascal(name), consts)
      nestedConst.set(name, out)
      preloads.set(out, `${fileOf(name)}.gd`)
    }
    return out
  }

  const signals: string[] = []
  const vars: string[] = []
  schema.fields.forEach((field, i) => {
    const member = members[i] ?? ""
    const parsed = parseFieldType(field.type)
    if (parsed === undefined) {
      throw new CodegenError(
        `${schema.name}.${field.name}: bad type ${field.type}`,
      )
    }
    vars.push(`## \`${field.name}\`: ${field.type}.`)
    if (parsed.kind === "primitive" || parsed.kind === "int") {
      const { type, zero } = scalar(parsed.type)
      const signal = claim(`${member}_changed`, taken)
      signals.push(
        `## \`${field.name}\` changed; emitted after the frame is applied.`,
        `signal ${signal}(value: ${type}, previous: ${type})`,
      )
      vars.push(`var ${member}: ${type} = ${zero}`)
    } else if (parsed.kind === "schema") {
      vars.push(`var ${member} = ${classConst(parsed.schema)}.new()`)
    } else {
      const kind = parsed.kind.replace("schema", "").toLowerCase()
      vars.push(
        `var ${member} = ${collectionConst(kind)}.new(${literal(field.type)})`,
      )
    }
  })

  const lines = [
    ...header(options, literal(`${replica}/schema.gd`)),
    `## Schema class \`${schema.name}\`.`,
    "",
  ]
  for (const [name, path] of [...preloads].sort(([a], [b]) =>
    a < b ? -1 : 1,
  )) {
    lines.push(`const ${name} = preload(${literal(path)})`)
  }
  if (preloads.size > 0) lines.push("")
  lines.push(
    "## The class's name on the wire.",
    `const SCHEMA_NAME := ${literal(schema.name)}`,
    "## [wire name, type, member]: matched by name against the server's DEFINE.",
    "const FIELDS := [",
    ...schema.fields.map(
      (field, i) =>
        `\t[${literal(field.name)}, ${literal(field.type)}, ${literal(members[i] ?? "")}],`,
    ),
    "]",
  )
  if (signals.length > 0) lines.push("", ...signals)
  if (vars.length > 0) lines.push("", ...vars)
  return text(lines)
}

// ===========================================================================
// Messages
// ===========================================================================

function isIdentity(field: Field): boolean {
  switch (field.kind) {
    case "nested":
      return false
    case "array":
    case "map":
    case "optional":
      return isIdentity(field.of)
    default:
      return true
  }
}

class MessageScript {
  private readonly _consts = new Set(["Contract", "Payloads", "MESSAGE_NAME"])
  private readonly _nested = new Map<string, string>()
  private readonly _preloads = new Map<string, string>()

  public constructor(
    private readonly def: MessageDef,
    private readonly options: GDScriptOptions,
    private readonly fileOf: (def: MessageDef) => string,
  ) {}

  public emit(): string {
    const def = this.def
    const taken = new Set([
      ...RESERVED,
      "definition",
      "to_payload",
      "from_payload",
      "encode",
      "decode",
    ])
    const members = def.fieldNames.map((name) => claim(snake(name), taken))
    const enumConsts: string[] = []
    const vars: string[] = []
    const toLines: string[] = []
    const fromLines: string[] = []
    const declLines: string[] = []
    def.fieldNames.forEach((name, i) => {
      const field = def.fields[name]
      if (field === undefined) return
      const member = members[i] ?? ""
      declLines.push(`\t\t\t[${literal(name)}, ${this._fieldType(field)}],`)
      const found = findEnum(field)
      if (found !== undefined) {
        const constName = claim(`${upperSnake(member)}_VALUES`, this._consts)
        enumConsts.push(
          `## Values of \`${name}\`, in index order.`,
          `const ${constName} := [${found.values.map((v) => (typeof v === "string" ? literal(v) : String(v))).join(", ")}]`,
        )
      }
      vars.push(`## \`${name}\`: ${typeText(field)}.`)
      if (field.kind === "optional") {
        vars.push(`var ${member} = null`)
        toLines.push(
          `\tif ${member} != null:`,
          `\t\tpayload[${literal(name)}] = ${this._to(field.of, member, 0)}`,
        )
        fromLines.push(
          `\tif payload.get(${literal(name)}) != null:`,
          `\t\tmessage.${member} = ${this._from(field.of, `payload[${literal(name)}]`, 0)}`,
        )
      } else {
        vars.push(`var ${member}${this._typed(field)}`)
        toLines.push(
          `\tpayload[${literal(name)}] = ${this._to(field, member, 0)}`,
        )
        fromLines.push(
          `\tmessage.${member} = ${this._from(field, `payload.get(${literal(name)})`, 0)}`,
        )
      }
    })

    const addon = `${this.options.addon}/protocol`
    const lines = [
      ...header(this.options, "RefCounted"),
      `## Contract message \`${def.name}\`.`,
      "",
      `const Contract = preload(${literal(`${addon}/contract.gd`)})`,
      `const Payloads = preload(${literal(`${addon}/payloads.gd`)})`,
    ]
    for (const [name, path] of [...this._preloads].sort(([a], [b]) =>
      a < b ? -1 : 1,
    )) {
      lines.push(`const ${name} = preload(${literal(path)})`)
    }
    lines.push(
      "",
      "## The message's name on the wire; its id comes from the handshake.",
      `const MESSAGE_NAME := ${literal(def.name)}`,
      ...enumConsts,
      "",
      "static var _definition = null",
    )
    if (vars.length > 0) lines.push("", ...vars)
    lines.push(
      "",
      "",
      "## The declaration the codecs encode with.",
      "static func definition():",
      "\tif _definition == null:",
      `\t\t_definition = Contract.message(MESSAGE_NAME, [`,
      ...declLines,
      "\t\t])",
      "\treturn _definition",
      "",
      "",
      "func to_payload() -> Dictionary:",
      "\tvar payload := {}",
      ...toLines,
      "\treturn payload",
      "",
      "",
      "static func from_payload(payload: Dictionary):",
      "\tvar message = new()",
      ...fromLines,
      "\treturn message",
      "",
      "",
      "## Encodes with the room's codec: a Result holding the bytes.",
      "func encode(codec):",
      "\treturn codec.encode_message(definition(), to_payload())",
      "",
      "",
      "## Decodes a body with the room's codec: a Result holding the message.",
      "static func decode(codec, body: PackedByteArray):",
      "\tvar decoded = codec.decode_message(definition(), body)",
      "\tif decoded.ok:",
      "\t\tdecoded.value = from_payload(decoded.value)",
      "\treturn decoded",
    )
    return text(lines)
  }

  private _nestedConst(def: MessageDef): string {
    let out = this._nested.get(def.name)
    if (out === undefined) {
      out = claim(`${pascal(def.name)}Message`, this._consts)
      this._nested.set(def.name, out)
      this._preloads.set(out, `${this.fileOf(def)}.gd`)
    }
    return out
  }

  private _typed(field: Field): string {
    switch (field.kind) {
      case "array":
        return ": Array = []"
      case "map":
        return ": Dictionary = {}"
      case "nested":
        return ` = ${this._nestedConst(field.message)}.new()`
      case "enum": {
        const first = field.values[0]
        return ` = ${typeof first === "string" ? literal(first) : String(first)}`
      }
      default: {
        const { type, zero } = scalar(
          field.kind === "fixed" ? "fixed:0" : field.kind,
        )
        return `: ${type} = ${zero}`
      }
    }
  }

  private _fieldType(field: Field): string {
    switch (field.kind) {
      case "fixed":
        return `Contract.fixed(${field.decimals})`
      case "enum":
        return `Contract.enum_of([${field.values.map((v) => (typeof v === "string" ? literal(v) : String(v))).join(", ")}])`
      case "array":
        return `Contract.array_of(${this._fieldType(field.of)})`
      case "map":
        return `Contract.map_of(${this._fieldType(field.of)})`
      case "optional":
        return `Contract.optional_of(${this._fieldType(field.of)})`
      case "nested":
        return `Contract.nested(${this._nestedConst(field.message)}.definition())`
      case "bool":
        return "Contract.bool_()"
      default:
        return `Contract.${field.kind}()`
    }
  }

  /** Member value → payload value. */
  private _to(field: Field, expr: string, depth: number): string {
    const x = `x${depth}`
    switch (field.kind) {
      case "array":
        return isIdentity(field.of)
          ? `${expr}.duplicate()`
          : `Payloads.map_list(${expr}, func(${x}): return ${this._to(field.of, x, depth + 1)})`
      case "map":
        return isIdentity(field.of)
          ? `${expr}.duplicate()`
          : `Payloads.map_values(${expr}, func(${x}): return ${this._to(field.of, x, depth + 1)})`
      case "optional":
        return isIdentity(field.of)
          ? expr
          : `(null if ${expr} == null else ${this._to(field.of, expr, depth)})`
      case "nested":
        return `${expr}.to_payload()`
      default:
        return expr
    }
  }

  /** Payload value → member value. */
  private _from(field: Field, expr: string, depth: number): string {
    const x = `x${depth}`
    switch (field.kind) {
      case "array":
        return isIdentity(field.of)
          ? `Payloads.map_list(${expr}, func(${x}): return ${x})`
          : `Payloads.map_list(${expr}, func(${x}): return ${this._from(field.of, x, depth + 1)})`
      case "map":
        return isIdentity(field.of)
          ? `Payloads.map_values(${expr}, func(${x}): return ${x})`
          : `Payloads.map_values(${expr}, func(${x}): return ${this._from(field.of, x, depth + 1)})`
      case "optional":
        return isIdentity(field.of)
          ? expr
          : `(null if ${expr} == null else ${this._from(field.of, expr, depth)})`
      case "nested":
        return `${this._nestedConst(field.message)}.from_payload(${expr})`
      default:
        return expr
    }
  }
}

function findEnum(field: Field): Extract<Field, { kind: "enum" }> | undefined {
  switch (field.kind) {
    case "enum":
      return field
    case "array":
    case "map":
    case "optional":
      return findEnum(field.of)
    default:
      return undefined
  }
}

// ===========================================================================
// Contracts and the index
// ===========================================================================

function contractScript(
  contract: CodegenModel["contracts"][number],
  options: GDScriptOptions,
  messageConst: (def: MessageDef) => string,
  messageFile: (def: MessageDef) => string,
): string {
  const defs = [...new Set([...contract.client, ...contract.server])].sort(
    (a, b) => (a.name < b.name ? -1 : 1),
  )
  const table = (list: readonly MessageDef[]): string[] =>
    list.map((def) => `\t${literal(def.name)}: ${messageConst(def)},`)
  return text([
    ...header(options, "RefCounted"),
    `## Contract \`${contract.name}\`.`,
    "",
    `const Result = preload(${literal(`${options.addon}/protocol/result.gd`)})`,
    ...defs.map(
      (def) =>
        `const ${messageConst(def)} = preload(${literal(`../${messageFile(def)}.gd`)})`,
    ),
    "",
    "## The contract hash this client was built against: sent in JOIN and",
    "## compared with the handshake's. Message ids are not generated: they",
    "## come from the handshake and are resolved by name.",
    `const HASH := ${literal(contract.hash)}`,
    "## Client → server messages, by name.",
    "const CLIENT := {",
    ...table(contract.client),
    "}",
    "## Server → client messages, by name.",
    "const SERVER := {",
    ...table(contract.server),
    "}",
    "",
    "",
    "## Decodes a server message by name (resolved from its id through the",
    "## handshake's table): a Result holding the message.",
    "static func decode_server(codec, name: String, body: PackedByteArray):",
    "\treturn _decode(SERVER, codec, name, body)",
    "",
    "",
    "static func decode_client(codec, name: String, body: PackedByteArray):",
    "\treturn _decode(CLIENT, codec, name, body)",
    "",
    "",
    "static func _decode(table: Dictionary, codec, name: String, body: PackedByteArray):",
    "\tif not table.has(name):",
    '\t\treturn Result.failure(Result.DECODE_FAILED, "no message named " + name)',
    "\treturn table[name].decode(codec, body)",
  ])
}

export function generateGDScript(
  model: CodegenModel,
  options: GDScriptOptions,
): Map<string, string> {
  const files = new Map<string, string>()
  const paths = new Set<string>()
  const schemaFiles = new Map<string, string>()
  for (const schema of model.schemas) {
    schemaFiles.set(schema.name, claim(`schemas/${snake(schema.name)}`, paths))
  }
  const messageFiles = new Map<string, string>()
  for (const def of model.messages) {
    messageFiles.set(
      def.name,
      claim(`messages/${snake(def.name)}_message`, paths),
    )
  }
  const contractFiles = new Map<string, string>()
  for (const contract of model.contracts) {
    contractFiles.set(
      contract.name,
      claim(`contracts/${snake(contract.name)}`, paths),
    )
  }
  const schemaFile = (name: string): string => {
    const out = schemaFiles.get(name)
    if (out === undefined)
      throw new CodegenError(`unknown schema class ${name}`)
    return out
  }
  const messageFile = (def: MessageDef): string => {
    const out = messageFiles.get(def.name)
    if (out === undefined) throw new CodegenError(`unknown message ${def.name}`)
    return out
  }
  // Paths relative to the script that preloads them.
  const sibling = (path: string): string => path.slice(path.indexOf("/") + 1)

  for (const schema of model.schemas) {
    files.set(
      `${schemaFile(schema.name)}.gd`,
      schemaScript(schema, options, (name) => sibling(schemaFile(name))),
    )
  }
  for (const def of model.messages) {
    files.set(
      `${messageFile(def)}.gd`,
      new MessageScript(def, options, (d) => sibling(messageFile(d))).emit(),
    )
  }

  // bindings.gd: one const per class.
  const consts = new Set(["SchemaRegistry", "SCHEMAS"])
  const schemaConst = new Map<string, string>()
  for (const schema of model.schemas) {
    schemaConst.set(schema.name, claim(pascal(schema.name), consts))
  }
  const messageConstNames = new Map<string, string>()
  for (const def of model.messages) {
    messageConstNames.set(def.name, claim(`${pascal(def.name)}Message`, consts))
  }
  const messageConst = (def: MessageDef): string =>
    messageConstNames.get(def.name) ?? ""
  const contractConst = new Map<string, string>()
  for (const contract of model.contracts) {
    contractConst.set(contract.name, claim(pascal(contract.name), consts))
  }
  for (const contract of model.contracts) {
    files.set(
      `${contractFiles.get(contract.name) ?? ""}.gd`,
      contractScript(contract, options, messageConst, messageFile),
    )
  }

  const index = [
    ...header(options, "RefCounted"),
    "## Everything generated, preloaded:",
    "##",
    '##     const Bindings = preload("res://…/bindings.gd")',
    "##     var registry = Bindings.create_registry()",
    "",
    `const SchemaRegistry = preload(${literal(`${options.addon}/replica/schema_registry.gd`)})`,
    "",
    ...model.schemas.map(
      (s) =>
        `const ${schemaConst.get(s.name)} = preload(${literal(`${schemaFile(s.name)}.gd`)})`,
    ),
    ...model.messages.map(
      (d) =>
        `const ${messageConst(d)} = preload(${literal(`${messageFile(d)}.gd`)})`,
    ),
    ...model.contracts.map(
      (c) =>
        `const ${contractConst.get(c.name)} = preload(${literal(`${contractFiles.get(c.name)}.gd`)})`,
    ),
    "",
    "## Every schema class.",
    `const SCHEMAS := [${model.schemas.map((s) => schemaConst.get(s.name)).join(", ")}]`,
    "",
    "",
    "## A registry holding every schema class, so the replica can instantiate",
    "## what the server sends.",
    "static func create_registry():",
    "\tvar registry = SchemaRegistry.new()",
    "\tfor schema in SCHEMAS:",
    "\t\tregistry.register(schema)",
    "\treturn registry",
  ]
  files.set("bindings.gd", text(index))
  if (paths.size + 1 !== files.size) {
    throw new CodegenError("generated file names collide")
  }
  return files
}
