# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Everything generated, preloaded:
##
##     const Bindings = preload("res://…/bindings.gd")
##     var registry = Bindings.create_registry()

const SchemaRegistry = preload("res://addons/bungohan/replica/schema_registry.gd")

const Interop_Player = preload("schemas/interop_player.gd")
const Interop_State = preload("schemas/interop_state.gd")
const AddTagMessage = preload("messages/add_tag_message.gd")
const BumpMessage = preload("messages/bump_message.gd")
const DropMeMessage = preload("messages/drop_me_message.gd")
const DumpMessage = preload("messages/dump_message.gd")
const EchoMessage = preload("messages/echo_message.gd")
const EchoedMessage = preload("messages/echoed_message.gd")
const KickMeMessage = preload("messages/kick_me_message.gd")
const MoveMessage = preload("messages/move_message.gd")
const PlayerDumpMessage = preload("messages/player_dump_message.gd")
const RequestDumpMessage = preload("messages/request_dump_message.gd")
const SetNameMessage = preload("messages/set_name_message.gd")
const WelcomeMessage = preload("messages/welcome_message.gd")
const InteropContract = preload("contracts/interop_contract.gd")

## Every schema class.
const SCHEMAS := [Interop_Player, Interop_State]


## A registry holding every schema class, so the replica can instantiate
## what the server sends.
static func create_registry():
	var registry = SchemaRegistry.new()
	for schema in SCHEMAS:
		registry.register(schema)
	return registry
