# Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `Everything`.

const ArraySchema = preload("res://addons/bungohan/replica/array_schema.gd")
const G_Vec = preload("g_vec.gd")
const MapSchema = preload("res://addons/bungohan/replica/map_schema.gd")
const SetSchema = preload("res://addons/bungohan/replica/set_schema.gd")

## The class's name on the wire.
const SCHEMA_NAME := "Everything"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["f64", "float64", "f64"],
	["f32", "float32", "f32"],
	["fx", "fixed:2", "fx"],
	["str", "string", "str"],
	["flag", "bool", "flag"],
	["i8", "int8", "i8"],
	["i16", "int16", "i16"],
	["i32", "int32", "i32"],
	["u8", "uint8", "u8"],
	["u16", "uint16", "u16"],
	["u32", "uint32", "u32"],
	["pos", "schema<G.Vec>", "pos"],
	["byName", "map<string,fixed:1>", "by_name"],
	["byId", "map<uint32,bool>", "by_id"],
	["byF64", "map<float64,string>", "by_f64"],
	["ids", "set<int32>", "ids"],
	["ratios", "array<float32>", "ratios"],
	["items", "schemaMap<string,Item>", "items"],
	["itemSet", "schemaSet<Item>", "item_set"],
	["itemList", "schemaArray<Item>", "item_list"],
	["get_", "string", "get_"],
	["definition", "float64", "definition"],
	["class", "bool", "class_"],
	["applyField", "uint8", "apply_field"],
	["countChanged", "float64", "count_changed"],
]

## `f64` changed; emitted after the frame is applied.
signal f64_changed(value: float, previous: float)
## `f32` changed; emitted after the frame is applied.
signal f32_changed(value: float, previous: float)
## `fx` changed; emitted after the frame is applied.
signal fx_changed(value: float, previous: float)
## `str` changed; emitted after the frame is applied.
signal str_changed(value: String, previous: String)
## `flag` changed; emitted after the frame is applied.
signal flag_changed(value: bool, previous: bool)
## `i8` changed; emitted after the frame is applied.
signal i8_changed(value: int, previous: int)
## `i16` changed; emitted after the frame is applied.
signal i16_changed(value: int, previous: int)
## `i32` changed; emitted after the frame is applied.
signal i32_changed(value: int, previous: int)
## `u8` changed; emitted after the frame is applied.
signal u8_changed(value: int, previous: int)
## `u16` changed; emitted after the frame is applied.
signal u16_changed(value: int, previous: int)
## `u32` changed; emitted after the frame is applied.
signal u32_changed(value: int, previous: int)
## `get_` changed; emitted after the frame is applied.
signal get__changed(value: String, previous: String)
## `definition` changed; emitted after the frame is applied.
signal definition_changed(value: float, previous: float)
## `class` changed; emitted after the frame is applied.
signal class__changed(value: bool, previous: bool)
## `applyField` changed; emitted after the frame is applied.
signal apply_field_changed(value: int, previous: int)
## `countChanged` changed; emitted after the frame is applied.
signal count_changed_changed(value: float, previous: float)

## `f64`: float64.
var f64: float = 0.0
## `f32`: float32.
var f32: float = 0.0
## `fx`: fixed:2.
var fx: float = 0.0
## `str`: string.
var str: String = ""
## `flag`: bool.
var flag: bool = false
## `i8`: int8.
var i8: int = 0
## `i16`: int16.
var i16: int = 0
## `i32`: int32.
var i32: int = 0
## `u8`: uint8.
var u8: int = 0
## `u16`: uint16.
var u16: int = 0
## `u32`: uint32.
var u32: int = 0
## `pos`: schema<G.Vec>.
var pos = G_Vec.new()
## `byName`: map<string,fixed:1>.
var by_name = MapSchema.new("map<string,fixed:1>")
## `byId`: map<uint32,bool>.
var by_id = MapSchema.new("map<uint32,bool>")
## `byF64`: map<float64,string>.
var by_f64 = MapSchema.new("map<float64,string>")
## `ids`: set<int32>.
var ids = SetSchema.new("set<int32>")
## `ratios`: array<float32>.
var ratios = ArraySchema.new("array<float32>")
## `items`: schemaMap<string,Item>.
var items = MapSchema.new("schemaMap<string,Item>")
## `itemSet`: schemaSet<Item>.
var item_set = SetSchema.new("schemaSet<Item>")
## `itemList`: schemaArray<Item>.
var item_list = ArraySchema.new("schemaArray<Item>")
## `get_`: string.
var get_: String = ""
## `definition`: float64.
var definition: float = 0.0
## `class`: bool.
var class_: bool = false
## `applyField`: uint8.
var apply_field: int = 0
## `countChanged`: float64.
var count_changed: float = 0.0
