# Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `G.Vec`.

## The class's name on the wire.
const SCHEMA_NAME := "G.Vec"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["x", "fixed:3", "x"],
	["y", "fixed:3", "y"],
]

## `x` changed; emitted after the frame is applied.
signal x_changed(value: float, previous: float)
## `y` changed; emitted after the frame is applied.
signal y_changed(value: float, previous: float)

## `x`: fixed:3.
var x: float = 0.0
## `y`: fixed:3.
var y: float = 0.0
