# Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends "res://addons/bungohan/replica/schema.gd"
## Schema class `Item`.

const SetSchema = preload("res://addons/bungohan/replica/set_schema.gd")

## The class's name on the wire.
const SCHEMA_NAME := "Item"
## [wire name, type, member]: matched by name against the server's DEFINE.
const FIELDS := [
	["label", "string", "label"],
	["count", "uint16", "count"],
	["tags", "set<string>", "tags"],
]

## `label` changed; emitted after the frame is applied.
signal label_changed(value: String, previous: String)
## `count` changed; emitted after the frame is applied.
signal count_changed(value: int, previous: int)

## `label`: string.
var label: String = ""
## `count`: uint16.
var count: int = 0
## `tags`: set<string>.
var tags = SetSchema.new("set<string>")
