// <auto-generated>
// Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
// Do not edit: regenerate instead.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Bungohan.Protocol;

namespace Bungohan.Codegen.Golden
{
    /// <summary>Contract message <c>everything</c>.</summary>
    public sealed partial class EverythingMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "everything";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("i8", FieldType.Int8),
            new MessageField("i16", FieldType.Int16),
            new MessageField("i32", FieldType.Int32),
            new MessageField("u8", FieldType.UInt8),
            new MessageField("u16", FieldType.UInt16),
            new MessageField("u32", FieldType.UInt32),
            new MessageField("f32", FieldType.Float32),
            new MessageField("f64", FieldType.Float64),
            new MessageField("fx", FieldType.Fixed(3)),
            new MessageField("text", FieldType.String),
            new MessageField("flag", FieldType.Bool),
            new MessageField("color", FieldType.Enum("red", "green", "dark blue")),
            new MessageField("level", FieldType.Enum(1d, 5d, 10d)),
            new MessageField("list", FieldType.ArrayOf(FieldType.Int16)),
            new MessageField("names", FieldType.MapOf(FieldType.String)),
            new MessageField("maybe", FieldType.OptionalOf(FieldType.Fixed(1))),
            new MessageField("maybeFlag", FieldType.OptionalOf(FieldType.Bool)),
            new MessageField("maybeColor", FieldType.OptionalOf(FieldType.Enum("north", "south"))),
            new MessageField("maybePoint", FieldType.OptionalOf(FieldType.NestedOf(PointMessage.Definition))),
            new MessageField("holes", FieldType.ArrayOf(FieldType.OptionalOf(FieldType.UInt8))),
            new MessageField("sparse", FieldType.MapOf(FieldType.OptionalOf(FieldType.Bool))),
            new MessageField("point", FieldType.NestedOf(PointMessage.Definition)),
            new MessageField("path", FieldType.ArrayOf(FieldType.NestedOf(PointMessage.Definition))),
            new MessageField("grid", FieldType.ArrayOf(FieldType.ArrayOf(FieldType.Float64))),
            new MessageField("tagged", FieldType.MapOf(FieldType.ArrayOf(FieldType.NestedOf(PointMessage.Definition)))),
            new MessageField("palette", FieldType.ArrayOf(FieldType.Enum("red", "blue"))),
            new MessageField("definition", FieldType.String),
            new MessageField("encode", FieldType.Bool));

        /// <summary>The values of <see cref="ColorValue"/>, in index order.</summary>
        private static readonly object[] s_colorValues = { "red", "green", "dark blue" };

        public enum ColorValue
        {
            /// <summary><c>"red"</c></summary>
            Red = 0,
            /// <summary><c>"green"</c></summary>
            Green = 1,
            /// <summary><c>"dark blue"</c></summary>
            Dark_blue = 2,
        }

        /// <summary>The values of <see cref="MaybeColorValue"/>, in index order.</summary>
        private static readonly object[] s_maybeColorValues = { "north", "south" };

        public enum MaybeColorValue
        {
            /// <summary><c>"north"</c></summary>
            North = 0,
            /// <summary><c>"south"</c></summary>
            South = 1,
        }

        /// <summary>The values of <see cref="PaletteValue"/>, in index order.</summary>
        private static readonly object[] s_paletteValues = { "red", "blue" };

        public enum PaletteValue
        {
            /// <summary><c>"red"</c></summary>
            Red = 0,
            /// <summary><c>"blue"</c></summary>
            Blue = 1,
        }

        /// <summary><c>i8</c>: <c>int8</c>.</summary>
        public sbyte I8 { get; set; }

        /// <summary><c>i16</c>: <c>int16</c>.</summary>
        public short I16 { get; set; }

        /// <summary><c>i32</c>: <c>int32</c>.</summary>
        public int I32 { get; set; }

        /// <summary><c>u8</c>: <c>uint8</c>.</summary>
        public byte U8 { get; set; }

        /// <summary><c>u16</c>: <c>uint16</c>.</summary>
        public ushort U16 { get; set; }

        /// <summary><c>u32</c>: <c>uint32</c>.</summary>
        public uint U32 { get; set; }

        /// <summary><c>f32</c>: <c>float32</c>.</summary>
        public float F32 { get; set; }

        /// <summary><c>f64</c>: <c>float64</c>.</summary>
        public double F64 { get; set; }

        /// <summary><c>fx</c>: <c>fixed:3</c>.</summary>
        public double Fx { get; set; }

        /// <summary><c>text</c>: <c>string</c>.</summary>
        public string Text { get; set; } = "";

        /// <summary><c>flag</c>: <c>bool</c>.</summary>
        public bool Flag { get; set; }

        /// <summary><c>color</c>: <c>enum["red"|"green"|"dark blue"]</c>.</summary>
        public ColorValue Color { get; set; }

        /// <summary><c>level</c>: <c>enum[1|5|10]</c>.</summary>
        public double Level { get; set; }

        /// <summary><c>list</c>: <c>array&lt;int16&gt;</c>.</summary>
        public List<short> List { get; set; } = new List<short>();

        /// <summary><c>names</c>: <c>map&lt;string&gt;</c>.</summary>
        public Dictionary<string, string> Names { get; set; } = new Dictionary<string, string>();

        /// <summary><c>maybe</c>: <c>optional&lt;fixed:1&gt;</c>.</summary>
        public double? Maybe { get; set; }

        /// <summary><c>maybeFlag</c>: <c>optional&lt;bool&gt;</c>.</summary>
        public bool? MaybeFlag { get; set; }

        /// <summary><c>maybeColor</c>: <c>optional&lt;enum["north"|"south"]&gt;</c>.</summary>
        public MaybeColorValue? MaybeColor { get; set; }

        /// <summary><c>maybePoint</c>: <c>optional&lt;nested&lt;point&gt;&gt;</c>.</summary>
        public PointMessage? MaybePoint { get; set; }

        /// <summary><c>holes</c>: <c>array&lt;optional&lt;uint8&gt;&gt;</c>.</summary>
        public List<byte?> Holes { get; set; } = new List<byte?>();

        /// <summary><c>sparse</c>: <c>map&lt;optional&lt;bool&gt;&gt;</c>.</summary>
        public Dictionary<string, bool?> Sparse { get; set; } = new Dictionary<string, bool?>();

        /// <summary><c>point</c>: <c>nested&lt;point&gt;</c>.</summary>
        public PointMessage Point { get; set; } = new PointMessage();

        /// <summary><c>path</c>: <c>array&lt;nested&lt;point&gt;&gt;</c>.</summary>
        public List<PointMessage> Path { get; set; } = new List<PointMessage>();

        /// <summary><c>grid</c>: <c>array&lt;array&lt;float64&gt;&gt;</c>.</summary>
        public List<List<double>> Grid { get; set; } = new List<List<double>>();

        /// <summary><c>tagged</c>: <c>map&lt;array&lt;nested&lt;point&gt;&gt;&gt;</c>.</summary>
        public Dictionary<string, List<PointMessage>> Tagged { get; set; } = new Dictionary<string, List<PointMessage>>();

        /// <summary><c>palette</c>: <c>array&lt;enum["red"|"blue"]&gt;</c>.</summary>
        public List<PaletteValue> Palette { get; set; } = new List<PaletteValue>();

        /// <summary><c>definition</c>: <c>string</c>.</summary>
        public string Definition_ { get; set; } = "";

        /// <summary><c>encode</c>: <c>bool</c>.</summary>
        public bool Encode_ { get; set; }

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["i8"] = I8;
            payload["i16"] = I16;
            payload["i32"] = I32;
            payload["u8"] = U8;
            payload["u16"] = U16;
            payload["u32"] = U32;
            payload["f32"] = F32;
            payload["f64"] = F64;
            payload["fx"] = Fx;
            payload["text"] = Text;
            payload["flag"] = Flag;
            payload["color"] = s_colorValues[(int)Color];
            payload["level"] = Level;
            payload["list"] = Payloads.FromList(List, x0 => (object?)x0);
            payload["names"] = Payloads.FromMap(Names, x0 => (object?)x0);
            if (Maybe != null) payload["maybe"] = Maybe.Value;
            if (MaybeFlag != null) payload["maybeFlag"] = MaybeFlag.Value;
            if (MaybeColor != null) payload["maybeColor"] = s_maybeColorValues[(int)MaybeColor.Value];
            if (MaybePoint != null) payload["maybePoint"] = MaybePoint.ToPayload();
            payload["holes"] = Payloads.FromList(Holes, x0 => (object?)(x0.HasValue ? (object?)x0.Value : null));
            payload["sparse"] = Payloads.FromMap(Sparse, x0 => (object?)(x0.HasValue ? (object?)x0.Value : null));
            payload["point"] = Point.ToPayload();
            payload["path"] = Payloads.FromList(Path, x0 => (object?)x0.ToPayload());
            payload["grid"] = Payloads.FromList(Grid, x0 => (object?)Payloads.FromList(x0, x1 => (object?)x1));
            payload["tagged"] = Payloads.FromMap(Tagged, x0 => (object?)Payloads.FromList(x0, x1 => (object?)x1.ToPayload()));
            payload["palette"] = Payloads.FromList(Palette, x0 => (object?)s_paletteValues[(int)x0]);
            payload["definition"] = Definition_;
            payload["encode"] = Encode_;
            return payload;
        }

        public static EverythingMessage FromPayload(MsgMap payload)
        {
            var message = new EverythingMessage();
            message.I8 = (sbyte)Payloads.ToLong(payload["i8"]);
            message.I16 = (short)Payloads.ToLong(payload["i16"]);
            message.I32 = (int)Payloads.ToLong(payload["i32"]);
            message.U8 = (byte)Payloads.ToLong(payload["u8"]);
            message.U16 = (ushort)Payloads.ToLong(payload["u16"]);
            message.U32 = (uint)Payloads.ToLong(payload["u32"]);
            message.F32 = (float)Payloads.ToDouble(payload["f32"]);
            message.F64 = Payloads.ToDouble(payload["f64"]);
            message.Fx = Payloads.ToDouble(payload["fx"]);
            message.Text = (payload["text"] as string ?? "");
            message.Flag = (payload["flag"] is true);
            message.Color = (ColorValue)Math.Max(0, Array.IndexOf(s_colorValues, payload["color"]));
            message.Level = Payloads.ToDouble(payload["level"]);
            message.List = Payloads.ToList<short>(payload["list"], x0 => (short)Payloads.ToLong(x0));
            message.Names = Payloads.ToDictionary<string>(payload["names"], x0 => (x0 as string ?? ""));
            message.Maybe = payload.TryGetValue("maybe", out object? v15) && v15 != null
                ? (double?)Payloads.ToDouble(v15)
                : null;
            message.MaybeFlag = payload.TryGetValue("maybeFlag", out object? v16) && v16 != null
                ? (bool?)(v16 is true)
                : null;
            message.MaybeColor = payload.TryGetValue("maybeColor", out object? v17) && v17 != null
                ? (MaybeColorValue?)(MaybeColorValue)Math.Max(0, Array.IndexOf(s_maybeColorValues, v17))
                : null;
            message.MaybePoint = payload.TryGetValue("maybePoint", out object? v18) && v18 != null
                ? (PointMessage?)PointMessage.FromPayload(Payloads.AsMap(v18))
                : null;
            message.Holes = Payloads.ToList<byte?>(payload["holes"], x0 => (x0 == null ? (byte?)null : (byte)Payloads.ToLong(x0)));
            message.Sparse = Payloads.ToDictionary<bool?>(payload["sparse"], x0 => (x0 == null ? (bool?)null : (x0 is true)));
            message.Point = PointMessage.FromPayload(Payloads.AsMap(payload["point"]));
            message.Path = Payloads.ToList<PointMessage>(payload["path"], x0 => PointMessage.FromPayload(Payloads.AsMap(x0)));
            message.Grid = Payloads.ToList<List<double>>(payload["grid"], x0 => Payloads.ToList<double>(x0, x1 => Payloads.ToDouble(x1)));
            message.Tagged = Payloads.ToDictionary<List<PointMessage>>(payload["tagged"], x0 => Payloads.ToList<PointMessage>(x0, x1 => PointMessage.FromPayload(Payloads.AsMap(x1))));
            message.Palette = Payloads.ToList<PaletteValue>(payload["palette"], x0 => (PaletteValue)Math.Max(0, Array.IndexOf(s_paletteValues, x0)));
            message.Definition_ = (payload["definition"] as string ?? "");
            message.Encode_ = (payload["encode"] is true);
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<EverythingMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<EverythingMessage>.Ok(FromPayload(decoded.Value)) : Result<EverythingMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>ping</c>.</summary>
    public sealed partial class PingMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "ping";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName);

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            return payload;
        }

        public static PingMessage FromPayload(MsgMap payload)
        {
            var message = new PingMessage();
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<PingMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<PingMessage>.Ok(FromPayload(decoded.Value)) : Result<PingMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>point</c>.</summary>
    public sealed partial class PointMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "point";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("x", FieldType.Fixed(2)),
            new MessageField("y", FieldType.Fixed(2)));

        /// <summary><c>x</c>: <c>fixed:2</c>.</summary>
        public double X { get; set; }

        /// <summary><c>y</c>: <c>fixed:2</c>.</summary>
        public double Y { get; set; }

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["x"] = X;
            payload["y"] = Y;
            return payload;
        }

        public static PointMessage FromPayload(MsgMap payload)
        {
            var message = new PointMessage();
            message.X = Payloads.ToDouble(payload["x"]);
            message.Y = Payloads.ToDouble(payload["y"]);
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<PointMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<PointMessage>.Ok(FromPayload(decoded.Value)) : Result<PointMessage>.Fail(decoded.Error!);
        }
    }
}
