// <auto-generated>
// Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
// Do not edit: regenerate instead.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Bungohan.Protocol;

namespace Bungohan.Codegen.Golden
{
    /// <summary>Schema class <c>Everything</c>.</summary>
    public sealed partial class Everything : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "Everything";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new Everything(),
            new SchemaField("f64", "float64"),
            new SchemaField("f32", "float32"),
            new SchemaField("fx", "fixed:2"),
            new SchemaField("str", "string"),
            new SchemaField("flag", "bool"),
            new SchemaField("i8", "int8"),
            new SchemaField("i16", "int16"),
            new SchemaField("i32", "int32"),
            new SchemaField("u8", "uint8"),
            new SchemaField("u16", "uint16"),
            new SchemaField("u32", "uint32"),
            new SchemaField("pos", "schema<G.Vec>"),
            new SchemaField("byName", "map<string,fixed:1>"),
            new SchemaField("byId", "map<uint32,bool>"),
            new SchemaField("byF64", "map<float64,string>"),
            new SchemaField("ids", "set<int32>"),
            new SchemaField("ratios", "array<float32>"),
            new SchemaField("items", "schemaMap<string,Item>"),
            new SchemaField("itemSet", "schemaSet<Item>"),
            new SchemaField("itemList", "schemaArray<Item>"),
            new SchemaField("get_", "string"),
            new SchemaField("definition", "float64"),
            new SchemaField("class", "bool"),
            new SchemaField("applyField", "uint8"),
            new SchemaField("countChanged", "float64"));

        public override SchemaClass Class => Definition;

        private double _f64;

        /// <summary><c>f64</c>: <c>float64</c>.</summary>
        public double F64 => _f64;

        /// <summary>F64 changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? F64Changed;

        private float _f32;

        /// <summary><c>f32</c>: <c>float32</c>.</summary>
        public float F32 => _f32;

        /// <summary>F32 changed: (value, previous), after the frame is applied.</summary>
        public event Action<float, float>? F32Changed;

        private double _fx;

        /// <summary><c>fx</c>: <c>fixed:2</c>.</summary>
        public double Fx => _fx;

        /// <summary>Fx changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? FxChanged;

        private string _str = "";

        /// <summary><c>str</c>: <c>string</c>.</summary>
        public string Str => _str;

        /// <summary>Str changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? StrChanged;

        private bool _flag;

        /// <summary><c>flag</c>: <c>bool</c>.</summary>
        public bool Flag => _flag;

        /// <summary>Flag changed: (value, previous), after the frame is applied.</summary>
        public event Action<bool, bool>? FlagChanged;

        private sbyte _i8;

        /// <summary><c>i8</c>: <c>int8</c>.</summary>
        public sbyte I8 => _i8;

        /// <summary>I8 changed: (value, previous), after the frame is applied.</summary>
        public event Action<sbyte, sbyte>? I8Changed;

        private short _i16;

        /// <summary><c>i16</c>: <c>int16</c>.</summary>
        public short I16 => _i16;

        /// <summary>I16 changed: (value, previous), after the frame is applied.</summary>
        public event Action<short, short>? I16Changed;

        private int _i32;

        /// <summary><c>i32</c>: <c>int32</c>.</summary>
        public int I32 => _i32;

        /// <summary>I32 changed: (value, previous), after the frame is applied.</summary>
        public event Action<int, int>? I32Changed;

        private byte _u8;

        /// <summary><c>u8</c>: <c>uint8</c>.</summary>
        public byte U8 => _u8;

        /// <summary>U8 changed: (value, previous), after the frame is applied.</summary>
        public event Action<byte, byte>? U8Changed;

        private ushort _u16;

        /// <summary><c>u16</c>: <c>uint16</c>.</summary>
        public ushort U16 => _u16;

        /// <summary>U16 changed: (value, previous), after the frame is applied.</summary>
        public event Action<ushort, ushort>? U16Changed;

        private uint _u32;

        /// <summary><c>u32</c>: <c>uint32</c>.</summary>
        public uint U32 => _u32;

        /// <summary>U32 changed: (value, previous), after the frame is applied.</summary>
        public event Action<uint, uint>? U32Changed;

        /// <summary><c>pos</c>: <c>schema&lt;G.Vec&gt;</c>.</summary>
        public G_Vec Pos { get; } = new G_Vec();

        /// <summary><c>byName</c>: <c>map&lt;string,fixed:1&gt;</c>.</summary>
        public MapSchema<string, double> ByName { get; } = new MapSchema<string, double>("map<string,fixed:1>");

        /// <summary><c>byId</c>: <c>map&lt;uint32,bool&gt;</c>.</summary>
        public MapSchema<uint, bool> ById { get; } = new MapSchema<uint, bool>("map<uint32,bool>");

        /// <summary><c>byF64</c>: <c>map&lt;float64,string&gt;</c>.</summary>
        public MapSchema<double, string> ByF64 { get; } = new MapSchema<double, string>("map<float64,string>");

        /// <summary><c>ids</c>: <c>set&lt;int32&gt;</c>.</summary>
        public SetSchema<int> Ids { get; } = new SetSchema<int>("set<int32>");

        /// <summary><c>ratios</c>: <c>array&lt;float32&gt;</c>.</summary>
        public ArraySchema<float> Ratios { get; } = new ArraySchema<float>("array<float32>");

        /// <summary><c>items</c>: <c>schemaMap&lt;string,Item&gt;</c>.</summary>
        public MapSchema<string, Item> Items { get; } = new MapSchema<string, Item>("schemaMap<string,Item>");

        /// <summary><c>itemSet</c>: <c>schemaSet&lt;Item&gt;</c>.</summary>
        public SetSchema<Item> ItemSet { get; } = new SetSchema<Item>("schemaSet<Item>");

        /// <summary><c>itemList</c>: <c>schemaArray&lt;Item&gt;</c>.</summary>
        public ArraySchema<Item> ItemList { get; } = new ArraySchema<Item>("schemaArray<Item>");

        private string _get_ = "";

        /// <summary><c>get_</c>: <c>string</c>.</summary>
        public string Get_ => _get_;

        /// <summary>Get_ changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? Get_Changed;

        private double _definition_;

        /// <summary><c>definition</c>: <c>float64</c>.</summary>
        public double Definition_ => _definition_;

        /// <summary>Definition_ changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? Definition_Changed;

        private bool _class_;

        /// <summary><c>class</c>: <c>bool</c>.</summary>
        public bool Class_ => _class_;

        /// <summary>Class_ changed: (value, previous), after the frame is applied.</summary>
        public event Action<bool, bool>? Class_Changed;

        private byte _applyField_;

        /// <summary><c>applyField</c>: <c>uint8</c>.</summary>
        public byte ApplyField_ => _applyField_;

        /// <summary>ApplyField_ changed: (value, previous), after the frame is applied.</summary>
        public event Action<byte, byte>? ApplyField_Changed;

        private double _countChanged;

        /// <summary><c>countChanged</c>: <c>float64</c>.</summary>
        public double CountChanged => _countChanged;

        /// <summary>CountChanged changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? CountChangedChanged;

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            0 => Apply(0, ref _f64, wire, changes, F64Changed),
            1 => Apply(1, ref _f32, wire, changes, F32Changed),
            2 => Apply(2, ref _fx, wire, changes, FxChanged),
            3 => Apply(3, ref _str, wire, changes, StrChanged),
            4 => Apply(4, ref _flag, wire, changes, FlagChanged),
            5 => Apply(5, ref _i8, wire, changes, I8Changed),
            6 => Apply(6, ref _i16, wire, changes, I16Changed),
            7 => Apply(7, ref _i32, wire, changes, I32Changed),
            8 => Apply(8, ref _u8, wire, changes, U8Changed),
            9 => Apply(9, ref _u16, wire, changes, U16Changed),
            10 => Apply(10, ref _u32, wire, changes, U32Changed),
            20 => Apply(20, ref _get_, wire, changes, Get_Changed),
            21 => Apply(21, ref _definition_, wire, changes, Definition_Changed),
            22 => Apply(22, ref _class_, wire, changes, Class_Changed),
            23 => Apply(23, ref _applyField_, wire, changes, ApplyField_Changed),
            24 => Apply(24, ref _countChanged, wire, changes, CountChangedChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            11 => Pos,
            12 => ByName,
            13 => ById,
            14 => ByF64,
            15 => Ids,
            16 => Ratios,
            17 => Items,
            18 => ItemSet,
            19 => ItemList,
            _ => null,
        };
    }

    /// <summary>Schema class <c>G.Vec</c>.</summary>
    public sealed partial class G_Vec : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "G.Vec";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new G_Vec(),
            new SchemaField("x", "fixed:3"),
            new SchemaField("y", "fixed:3"));

        public override SchemaClass Class => Definition;

        private double _x;

        /// <summary><c>x</c>: <c>fixed:3</c>.</summary>
        public double X => _x;

        /// <summary>X changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? XChanged;

        private double _y;

        /// <summary><c>y</c>: <c>fixed:3</c>.</summary>
        public double Y => _y;

        /// <summary>Y changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? YChanged;

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            0 => Apply(0, ref _x, wire, changes, XChanged),
            1 => Apply(1, ref _y, wire, changes, YChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            _ => null,
        };
    }

    /// <summary>Schema class <c>Item</c>.</summary>
    public sealed partial class Item : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "Item";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new Item(),
            new SchemaField("label", "string"),
            new SchemaField("count", "uint16"),
            new SchemaField("tags", "set<string>"));

        public override SchemaClass Class => Definition;

        private string _label = "";

        /// <summary><c>label</c>: <c>string</c>.</summary>
        public string Label => _label;

        /// <summary>Label changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? LabelChanged;

        private ushort _count;

        /// <summary><c>count</c>: <c>uint16</c>.</summary>
        public ushort Count => _count;

        /// <summary>Count changed: (value, previous), after the frame is applied.</summary>
        public event Action<ushort, ushort>? CountChanged;

        /// <summary><c>tags</c>: <c>set&lt;string&gt;</c>.</summary>
        public SetSchema<string> Tags { get; } = new SetSchema<string>("set<string>");

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            0 => Apply(0, ref _label, wire, changes, LabelChanged),
            1 => Apply(1, ref _count, wire, changes, CountChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            2 => Tags,
            _ => null,
        };
    }

    /// <summary>Every generated schema class.</summary>
    public static class Schemas
    {
        /// <summary>Registers every class, so the replica can instantiate what the server sends.</summary>
        public static SchemaRegistry Register(SchemaRegistry registry)
        {
            registry.Register(Everything.Definition);
            registry.Register(G_Vec.Definition);
            registry.Register(Item.Definition);
            return registry;
        }

        public static SchemaRegistry CreateRegistry() => Register(new SchemaRegistry());
    }
}
