# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `bump`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "bump"

static var _definition = null

## `by`: int32.
var by: int = 0
## `alive`: bool.
var alive: bool = false
## `note`: optional<string>.
var note = null


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["by", Contract.int32()],
			["alive", Contract.bool_()],
			["note", Contract.optional_of(Contract.string())],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["by"] = by
	payload["alive"] = alive
	if note != null:
		payload["note"] = note
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.by = payload.get("by")
	message.alive = payload.get("alive")
	if payload.get("note") != null:
		message.note = payload["note"]
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
