# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `dump`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")
const PlayerDumpMessage = preload("player_dump_message.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "dump"

static var _definition = null

## `turn`: uint32.
var turn: int = 0
## `label`: string.
var label: String = ""
## `log`: array<string>.
var log: Array = []
## `players`: array<nested<playerDump>>.
var players: Array = []


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["turn", Contract.uint32()],
			["label", Contract.string()],
			["log", Contract.array_of(Contract.string())],
			["players", Contract.array_of(Contract.nested(PlayerDumpMessage.definition()))],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["turn"] = turn
	payload["label"] = label
	payload["log"] = log.duplicate()
	payload["players"] = Payloads.map_list(players, func(x0): return x0.to_payload())
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.turn = payload.get("turn")
	message.label = payload.get("label")
	message.log = Payloads.map_list(payload.get("log"), func(x0): return x0)
	message.players = Payloads.map_list(payload.get("players"), func(x0): return PlayerDumpMessage.from_payload(x0))
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
