# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `echo`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "echo"

static var _definition = null

## `text`: string.
var text: String = ""
## `count`: int32.
var count: int = 0


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["text", Contract.string()],
			["count", Contract.int32()],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["text"] = text
	payload["count"] = count
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.text = payload.get("text")
	message.count = payload.get("count")
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
