# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `move`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "move"

static var _definition = null

## `dx`: fixed:2.
var dx: float = 0.0
## `dy`: fixed:2.
var dy: float = 0.0


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["dx", Contract.fixed(2)],
			["dy", Contract.fixed(2)],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["dx"] = dx
	payload["dy"] = dy
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.dx = payload.get("dx")
	message.dy = payload.get("dy")
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
