# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `optionsJoin`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "optionsJoin"

static var _definition = null

## `name`: string.
var name: String = ""
## `aim`: fixed:2.
var aim: float = 0.0
## `team`: optional<uint8>.
var team = null
## `spectator`: bool.
var spectator: bool = false


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["name", Contract.string()],
			["aim", Contract.fixed(2)],
			["team", Contract.optional_of(Contract.uint8())],
			["spectator", Contract.bool_()],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["name"] = name
	payload["aim"] = aim
	if team != null:
		payload["team"] = team
	payload["spectator"] = spectator
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.name = payload.get("name")
	message.aim = payload.get("aim")
	if payload.get("team") != null:
		message.team = payload["team"]
	message.spectator = payload.get("spectator")
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
