# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `optionsCreate`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "optionsCreate"
## Values of `mode`, in index order.
const MODE_VALUES := ["duel", "team"]

static var _definition = null

## `mode`: enum["duel"|"team"].
var mode = "duel"
## `rounds`: uint8.
var rounds: int = 0
## `friendlyFire`: bool.
var friendly_fire: bool = false


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["mode", Contract.enum_of(["duel", "team"])],
			["rounds", Contract.uint8()],
			["friendlyFire", Contract.bool_()],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["mode"] = mode
	payload["rounds"] = rounds
	payload["friendlyFire"] = friendly_fire
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.mode = payload.get("mode")
	message.rounds = payload.get("rounds")
	message.friendly_fire = payload.get("friendlyFire")
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
