# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `playerDump`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "playerDump"

static var _definition = null

## `id`: string.
var id: String = ""
## `name`: string.
var name: String = ""
## `x`: fixed:2.
var x: float = 0.0
## `y`: fixed:2.
var y: float = 0.0
## `score`: int32.
var score: int = 0
## `alive`: bool.
var alive: bool = false
## `tags`: array<string>.
var tags: Array = []


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["id", Contract.string()],
			["name", Contract.string()],
			["x", Contract.fixed(2)],
			["y", Contract.fixed(2)],
			["score", Contract.int32()],
			["alive", Contract.bool_()],
			["tags", Contract.array_of(Contract.string())],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["id"] = id
	payload["name"] = name
	payload["x"] = x
	payload["y"] = y
	payload["score"] = score
	payload["alive"] = alive
	payload["tags"] = tags.duplicate()
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.id = payload.get("id")
	message.name = payload.get("name")
	message.x = payload.get("x")
	message.y = payload.get("y")
	message.score = payload.get("score")
	message.alive = payload.get("alive")
	message.tags = Payloads.map_list(payload.get("tags"), func(x0): return x0)
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
