# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract message `welcome`.

const Contract = preload("res://addons/bungohan/protocol/contract.gd")
const Payloads = preload("res://addons/bungohan/protocol/payloads.gd")

## The message's name on the wire; its id comes from the handshake.
const MESSAGE_NAME := "welcome"

static var _definition = null

## `sessionId`: string.
var session_id: String = ""
## `players`: uint8.
var players: int = 0


## The declaration the codecs encode with.
static func definition():
	if _definition == null:
		_definition = Contract.message(MESSAGE_NAME, [
			["sessionId", Contract.string()],
			["players", Contract.uint8()],
		])
	return _definition


func to_payload() -> Dictionary:
	var payload := {}
	payload["sessionId"] = session_id
	payload["players"] = players
	return payload


static func from_payload(payload: Dictionary):
	var message = new()
	message.session_id = payload.get("sessionId")
	message.players = payload.get("players")
	return message


## Encodes with the room's codec: a Result holding the bytes.
func encode(codec):
	return codec.encode_message(definition(), to_payload())


## Decodes a body with the room's codec: a Result holding the message.
static func decode(codec, body: PackedByteArray):
	var decoded = codec.decode_message(definition(), body)
	if decoded.ok:
		decoded.value = from_payload(decoded.value)
	return decoded
