# Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Everything generated, preloaded:
##
##     const Bindings = preload("res://…/bindings.gd")
##     var registry = Bindings.create_registry()

const SchemaRegistry = preload("res://addons/bungohan/replica/schema_registry.gd")

const Everything = preload("schemas/everything.gd")
const G_Vec = preload("schemas/g_vec.gd")
const Item = preload("schemas/item.gd")
const EverythingMessage = preload("messages/everything_message.gd")
const PingMessage = preload("messages/ping_message.gd")
const PointMessage = preload("messages/point_message.gd")
const FixtureContract = preload("contracts/fixture_contract.gd")

## Every schema class.
const SCHEMAS := [Everything, G_Vec, Item]


## A registry holding every schema class, so the replica can instantiate
## what the server sends.
static func create_registry():
	var registry = SchemaRegistry.new()
	for schema in SCHEMAS:
		registry.register(schema)
	return registry
