# Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract `fixtureContract`.

const Result = preload("res://addons/bungohan/protocol/result.gd")
const EverythingMessage = preload("../messages/everything_message.gd")
const PingMessage = preload("../messages/ping_message.gd")
const PointMessage = preload("../messages/point_message.gd")

## The contract hash this client was built against: sent in JOIN and
## compared with the handshake's. Message ids are not generated: they
## come from the handshake and are resolved by name.
const HASH := "7b655744"
## Client → server messages, by name.
const CLIENT := {
	"everything": EverythingMessage,
	"ping": PingMessage,
}
## Server → client messages, by name.
const SERVER := {
	"point": PointMessage,
	"everything": EverythingMessage,
}


## Decodes a server message by name (resolved from its id through the
## handshake's table): a Result holding the message.
static func decode_server(codec, name: String, body: PackedByteArray):
	return _decode(SERVER, codec, name, body)


static func decode_client(codec, name: String, body: PackedByteArray):
	return _decode(CLIENT, codec, name, body)


static func _decode(table: Dictionary, codec, name: String, body: PackedByteArray):
	if not table.has(name):
		return Result.failure(Result.DECODE_FAILED, "no message named " + name)
	return table[name].decode(codec, body)
