# Generated by @bungohan/codegen from @bungohan/codegen/test/fixture/contract.ts and @bungohan/codegen/test/fixture/state.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract `optionsContract`.

const Result = preload("res://addons/bungohan/protocol/result.gd")
const TypedOptions = preload("res://addons/bungohan/protocol/typed_options.gd")
const LobbyMessage = preload("../messages/lobby_message.gd")
const PingMessage = preload("../messages/ping_message.gd")
const SeatMessage = preload("../messages/seat_message.gd")

## The contract hash this client was built against: sent in JOIN and
## compared with the handshake's. Message ids are not generated: they
## come from the handshake and are resolved by name.
const HASH := "ced4c41b"
## Client → server messages, by name.
const CLIENT := {
	"ping": PingMessage,
}
## Server → client messages, by name.
const SERVER := {
}


## Decodes a server message by name (resolved from its id through the
## handshake's table): a Result holding the message.
static func decode_server(codec, name: String, body: PackedByteArray):
	return _decode(SERVER, codec, name, body)


static func decode_client(codec, name: String, body: PackedByteArray):
	return _decode(CLIENT, codec, name, body)


static func _decode(table: Dictionary, codec, name: String, body: PackedByteArray):
	if not table.has(name):
		return Result.failure(Result.DECODE_FAILED, "no message named " + name)
	return table[name].decode(codec, body)


## Join options for join() and join_by_id() (typed options,
## PROTOCOL.md §6.2.1).
static func join_options(join: SeatMessage) -> TypedOptions:
	return TypedOptions.from_messages(join, null)


## Options for create() and join_or_create(): the create options for a
## room the join creates, and the join options.
static func create_options(create: LobbyMessage, join: SeatMessage) -> TypedOptions:
	return TypedOptions.from_messages(join, create)
