# Generated by @bungohan/codegen from @bungohan/testing/src/interop/shared.ts (bungohan.v1).
# Do not edit: regenerate instead.
extends RefCounted
## Contract `interopContract`.

const Result = preload("res://addons/bungohan/protocol/result.gd")
const AddTagMessage = preload("../messages/add_tag_message.gd")
const BumpMessage = preload("../messages/bump_message.gd")
const DropMeMessage = preload("../messages/drop_me_message.gd")
const DumpMessage = preload("../messages/dump_message.gd")
const EchoMessage = preload("../messages/echo_message.gd")
const EchoedMessage = preload("../messages/echoed_message.gd")
const KickMeMessage = preload("../messages/kick_me_message.gd")
const MoveMessage = preload("../messages/move_message.gd")
const RequestDumpMessage = preload("../messages/request_dump_message.gd")
const SetNameMessage = preload("../messages/set_name_message.gd")
const WelcomeMessage = preload("../messages/welcome_message.gd")

## The contract hash this client was built against: sent in JOIN and
## compared with the handshake's. Message ids are not generated: they
## come from the handshake and are resolved by name.
const HASH := "eef98c28"
## Client → server messages, by name.
const CLIENT := {
	"move": MoveMessage,
	"setName": SetNameMessage,
	"addTag": AddTagMessage,
	"bump": BumpMessage,
	"requestDump": RequestDumpMessage,
	"echo": EchoMessage,
	"kickMe": KickMeMessage,
	"dropMe": DropMeMessage,
}
## Server → client messages, by name.
const SERVER := {
	"welcome": WelcomeMessage,
	"dump": DumpMessage,
	"echoed": EchoedMessage,
}


## Decodes a server message by name (resolved from its id through the
## handshake's table): a Result holding the message.
static func decode_server(codec, name: String, body: PackedByteArray):
	return _decode(SERVER, codec, name, body)


static func decode_client(codec, name: String, body: PackedByteArray):
	return _decode(CLIENT, codec, name, body)


static func _decode(table: Dictionary, codec, name: String, body: PackedByteArray):
	if not table.has(name):
		return Result.failure(Result.DECODE_FAILED, "no message named " + name)
	return table[name].decode(codec, body)
