// <auto-generated>
// Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
// Do not edit: regenerate instead.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Bungohan.Protocol;

namespace Bungohan.Example.Shooter
{
    /// <summary>Contract <c>lobbyContract</c>.</summary>
    public static class LobbyContract
    {
        /// <summary>
        /// The contract hash this client was built against: sent in JOIN and
        /// compared with the handshake's. Message ids are not generated: they
        /// come from the handshake and are resolved by name.
        /// </summary>
        public const string Hash = "4342ab15";

        /// <summary>Client → server messages, by name.</summary>
        public static readonly IReadOnlyDictionary<string, MessageDef> ClientMessages = new Dictionary<string, MessageDef>
        {
            ["refreshRooms"] = RefreshRoomsMessage.Definition,
            ["joinByCode"] = JoinByCodeMessage.Definition,
        };

        /// <summary>Server → client messages, by name.</summary>
        public static readonly IReadOnlyDictionary<string, MessageDef> ServerMessages = new Dictionary<string, MessageDef>
        {
            ["roomFound"] = RoomFoundMessage.Definition,
            ["error"] = ErrorMessage.Definition,
        };

        /// <summary>Decodes a server message by name (resolved from its id through the handshake's table).</summary>
        public static Result<IContractMessage> DecodeServer(IStateCodec codec, string name, byte[] body)
        {
            switch (name)
            {
                case "roomFound":
                {
                    var decoded = RoomFoundMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "error":
                {
                    var decoded = ErrorMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                default:
                    return Result<IContractMessage>.Fail(ErrorCodes.DecodeFailed, "no server message named " + name);
            }
        }

        /// <summary>Decodes a client message by name (resolved from its id through the handshake's table).</summary>
        public static Result<IContractMessage> DecodeClient(IStateCodec codec, string name, byte[] body)
        {
            switch (name)
            {
                case "refreshRooms":
                {
                    var decoded = RefreshRoomsMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "joinByCode":
                {
                    var decoded = JoinByCodeMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                default:
                    return Result<IContractMessage>.Fail(ErrorCodes.DecodeFailed, "no client message named " + name);
            }
        }
    }

    /// <summary>Contract <c>shooterContract</c>.</summary>
    public static class ShooterContract
    {
        /// <summary>
        /// The contract hash this client was built against: sent in JOIN and
        /// compared with the handshake's. Message ids are not generated: they
        /// come from the handshake and are resolved by name.
        /// </summary>
        public const string Hash = "b70eb79a";

        /// <summary>Client → server messages, by name.</summary>
        public static readonly IReadOnlyDictionary<string, MessageDef> ClientMessages = new Dictionary<string, MessageDef>
        {
            ["input"] = InputMessage.Definition,
            ["ready"] = ReadyMessage.Definition,
            ["startGame"] = StartGameMessage.Definition,
        };

        /// <summary>Server → client messages, by name.</summary>
        public static readonly IReadOnlyDictionary<string, MessageDef> ServerMessages = new Dictionary<string, MessageDef>
        {
            ["playerJoined"] = PlayerJoinedMessage.Definition,
            ["playerLeft"] = PlayerLeftMessage.Definition,
            ["gameStarted"] = GameStartedMessage.Definition,
            ["gameEnded"] = GameEndedMessage.Definition,
        };

        /// <summary>Decodes a server message by name (resolved from its id through the handshake's table).</summary>
        public static Result<IContractMessage> DecodeServer(IStateCodec codec, string name, byte[] body)
        {
            switch (name)
            {
                case "playerJoined":
                {
                    var decoded = PlayerJoinedMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "playerLeft":
                {
                    var decoded = PlayerLeftMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "gameStarted":
                {
                    var decoded = GameStartedMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "gameEnded":
                {
                    var decoded = GameEndedMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                default:
                    return Result<IContractMessage>.Fail(ErrorCodes.DecodeFailed, "no server message named " + name);
            }
        }

        /// <summary>Decodes a client message by name (resolved from its id through the handshake's table).</summary>
        public static Result<IContractMessage> DecodeClient(IStateCodec codec, string name, byte[] body)
        {
            switch (name)
            {
                case "input":
                {
                    var decoded = InputMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "ready":
                {
                    var decoded = ReadyMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                case "startGame":
                {
                    var decoded = StartGameMessage.Decode(codec, body);
                    return decoded.IsOk ? Result<IContractMessage>.Ok(decoded.Value) : Result<IContractMessage>.Fail(decoded.Error!);
                }
                default:
                    return Result<IContractMessage>.Fail(ErrorCodes.DecodeFailed, "no client message named " + name);
            }
        }

        /// <summary>
        /// Join options for <c>JoinAsync</c> and <c>JoinByIdAsync</c> (typed
        /// options, PROTOCOL.md §6.2.1).
        /// </summary>
        public static TypedOptions JoinOptions(ShooterJoinOptionsMessage join) => new TypedOptions(join, null);

        /// <summary>
        /// Options for <c>CreateAsync</c> and <c>JoinOrCreateAsync</c>: the
        /// create options for a room the join creates, and the join options.
        /// </summary>
        public static TypedOptions CreateOptions(ShooterCreateOptionsMessage create, ShooterJoinOptionsMessage join) => new TypedOptions(join, create);
    }
}
