// <auto-generated>
// Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
// Do not edit: regenerate instead.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Bungohan.Protocol;

namespace Bungohan.Example.Shooter
{
    /// <summary>Contract message <c>error</c>.</summary>
    public sealed partial class ErrorMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "error";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("message", FieldType.String));

        /// <summary><c>message</c>: <c>string</c>.</summary>
        public string Message { get; set; } = "";

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["message"] = Message;
            return payload;
        }

        public static ErrorMessage FromPayload(MsgMap payload)
        {
            var message = new ErrorMessage();
            message.Message = (payload["message"] as string ?? "");
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<ErrorMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<ErrorMessage>.Ok(FromPayload(decoded.Value)) : Result<ErrorMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>gameEnded</c>.</summary>
    public sealed partial class GameEndedMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "gameEnded";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("results", FieldType.ArrayOf(FieldType.NestedOf(GameResultMessage.Definition))));

        /// <summary><c>results</c>: <c>array&lt;nested&lt;gameResult&gt;&gt;</c>.</summary>
        public List<GameResultMessage> Results { get; set; } = new List<GameResultMessage>();

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["results"] = Payloads.FromList(Results, x0 => (object?)x0.ToPayload());
            return payload;
        }

        public static GameEndedMessage FromPayload(MsgMap payload)
        {
            var message = new GameEndedMessage();
            message.Results = Payloads.ToList<GameResultMessage>(payload["results"], x0 => GameResultMessage.FromPayload(Payloads.AsMap(x0)));
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<GameEndedMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<GameEndedMessage>.Ok(FromPayload(decoded.Value)) : Result<GameEndedMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>gameResult</c>.</summary>
    public sealed partial class GameResultMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "gameResult";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("playerId", FieldType.String),
            new MessageField("playerName", FieldType.String),
            new MessageField("score", FieldType.Int32),
            new MessageField("rank", FieldType.UInt8),
            new MessageField("color", FieldType.String));

        /// <summary><c>playerId</c>: <c>string</c>.</summary>
        public string PlayerId { get; set; } = "";

        /// <summary><c>playerName</c>: <c>string</c>.</summary>
        public string PlayerName { get; set; } = "";

        /// <summary><c>score</c>: <c>int32</c>.</summary>
        public int Score { get; set; }

        /// <summary><c>rank</c>: <c>uint8</c>.</summary>
        public byte Rank { get; set; }

        /// <summary><c>color</c>: <c>string</c>.</summary>
        public string Color { get; set; } = "";

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["playerId"] = PlayerId;
            payload["playerName"] = PlayerName;
            payload["score"] = Score;
            payload["rank"] = Rank;
            payload["color"] = Color;
            return payload;
        }

        public static GameResultMessage FromPayload(MsgMap payload)
        {
            var message = new GameResultMessage();
            message.PlayerId = (payload["playerId"] as string ?? "");
            message.PlayerName = (payload["playerName"] as string ?? "");
            message.Score = (int)Payloads.ToLong(payload["score"]);
            message.Rank = (byte)Payloads.ToLong(payload["rank"]);
            message.Color = (payload["color"] as string ?? "");
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<GameResultMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<GameResultMessage>.Ok(FromPayload(decoded.Value)) : Result<GameResultMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>gameStarted</c>.</summary>
    public sealed partial class GameStartedMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "gameStarted";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName);

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            return payload;
        }

        public static GameStartedMessage FromPayload(MsgMap payload)
        {
            var message = new GameStartedMessage();
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<GameStartedMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<GameStartedMessage>.Ok(FromPayload(decoded.Value)) : Result<GameStartedMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>input</c>.</summary>
    public sealed partial class InputMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "input";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("up", FieldType.Bool),
            new MessageField("down", FieldType.Bool),
            new MessageField("left", FieldType.Bool),
            new MessageField("right", FieldType.Bool),
            new MessageField("rotation", FieldType.Fixed(2)),
            new MessageField("shooting", FieldType.Bool));

        /// <summary><c>up</c>: <c>bool</c>.</summary>
        public bool Up { get; set; }

        /// <summary><c>down</c>: <c>bool</c>.</summary>
        public bool Down { get; set; }

        /// <summary><c>left</c>: <c>bool</c>.</summary>
        public bool Left { get; set; }

        /// <summary><c>right</c>: <c>bool</c>.</summary>
        public bool Right { get; set; }

        /// <summary><c>rotation</c>: <c>fixed:2</c>.</summary>
        public double Rotation { get; set; }

        /// <summary><c>shooting</c>: <c>bool</c>.</summary>
        public bool Shooting { get; set; }

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["up"] = Up;
            payload["down"] = Down;
            payload["left"] = Left;
            payload["right"] = Right;
            payload["rotation"] = Rotation;
            payload["shooting"] = Shooting;
            return payload;
        }

        public static InputMessage FromPayload(MsgMap payload)
        {
            var message = new InputMessage();
            message.Up = (payload["up"] is true);
            message.Down = (payload["down"] is true);
            message.Left = (payload["left"] is true);
            message.Right = (payload["right"] is true);
            message.Rotation = Payloads.ToDouble(payload["rotation"]);
            message.Shooting = (payload["shooting"] is true);
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<InputMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<InputMessage>.Ok(FromPayload(decoded.Value)) : Result<InputMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>joinByCode</c>.</summary>
    public sealed partial class JoinByCodeMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "joinByCode";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("roomCode", FieldType.String));

        /// <summary><c>roomCode</c>: <c>string</c>.</summary>
        public string RoomCode { get; set; } = "";

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["roomCode"] = RoomCode;
            return payload;
        }

        public static JoinByCodeMessage FromPayload(MsgMap payload)
        {
            var message = new JoinByCodeMessage();
            message.RoomCode = (payload["roomCode"] as string ?? "");
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<JoinByCodeMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<JoinByCodeMessage>.Ok(FromPayload(decoded.Value)) : Result<JoinByCodeMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>playerJoined</c>.</summary>
    public sealed partial class PlayerJoinedMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "playerJoined";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("playerId", FieldType.String),
            new MessageField("playerName", FieldType.String));

        /// <summary><c>playerId</c>: <c>string</c>.</summary>
        public string PlayerId { get; set; } = "";

        /// <summary><c>playerName</c>: <c>string</c>.</summary>
        public string PlayerName { get; set; } = "";

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["playerId"] = PlayerId;
            payload["playerName"] = PlayerName;
            return payload;
        }

        public static PlayerJoinedMessage FromPayload(MsgMap payload)
        {
            var message = new PlayerJoinedMessage();
            message.PlayerId = (payload["playerId"] as string ?? "");
            message.PlayerName = (payload["playerName"] as string ?? "");
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<PlayerJoinedMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<PlayerJoinedMessage>.Ok(FromPayload(decoded.Value)) : Result<PlayerJoinedMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>playerLeft</c>.</summary>
    public sealed partial class PlayerLeftMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "playerLeft";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("playerId", FieldType.String));

        /// <summary><c>playerId</c>: <c>string</c>.</summary>
        public string PlayerId { get; set; } = "";

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["playerId"] = PlayerId;
            return payload;
        }

        public static PlayerLeftMessage FromPayload(MsgMap payload)
        {
            var message = new PlayerLeftMessage();
            message.PlayerId = (payload["playerId"] as string ?? "");
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<PlayerLeftMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<PlayerLeftMessage>.Ok(FromPayload(decoded.Value)) : Result<PlayerLeftMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>ready</c>.</summary>
    public sealed partial class ReadyMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "ready";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("isReady", FieldType.Bool));

        /// <summary><c>isReady</c>: <c>bool</c>.</summary>
        public bool IsReady { get; set; }

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["isReady"] = IsReady;
            return payload;
        }

        public static ReadyMessage FromPayload(MsgMap payload)
        {
            var message = new ReadyMessage();
            message.IsReady = (payload["isReady"] is true);
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<ReadyMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<ReadyMessage>.Ok(FromPayload(decoded.Value)) : Result<ReadyMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>refreshRooms</c>.</summary>
    public sealed partial class RefreshRoomsMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "refreshRooms";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName);

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            return payload;
        }

        public static RefreshRoomsMessage FromPayload(MsgMap payload)
        {
            var message = new RefreshRoomsMessage();
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<RefreshRoomsMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<RefreshRoomsMessage>.Ok(FromPayload(decoded.Value)) : Result<RefreshRoomsMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>roomFound</c>.</summary>
    public sealed partial class RoomFoundMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "roomFound";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("roomId", FieldType.String));

        /// <summary><c>roomId</c>: <c>string</c>.</summary>
        public string RoomId { get; set; } = "";

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["roomId"] = RoomId;
            return payload;
        }

        public static RoomFoundMessage FromPayload(MsgMap payload)
        {
            var message = new RoomFoundMessage();
            message.RoomId = (payload["roomId"] as string ?? "");
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<RoomFoundMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<RoomFoundMessage>.Ok(FromPayload(decoded.Value)) : Result<RoomFoundMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>shooterCreateOptions</c>.</summary>
    public sealed partial class ShooterCreateOptionsMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "shooterCreateOptions";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("roomName", FieldType.OptionalOf(FieldType.String)),
            new MessageField("maxPlayers", FieldType.UInt8),
            new MessageField("isPrivate", FieldType.Bool));

        /// <summary><c>roomName</c>: <c>optional&lt;string&gt;</c>.</summary>
        public string? RoomName { get; set; }

        /// <summary><c>maxPlayers</c>: <c>uint8</c>.</summary>
        public byte MaxPlayers { get; set; }

        /// <summary><c>isPrivate</c>: <c>bool</c>.</summary>
        public bool IsPrivate { get; set; }

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            if (RoomName != null) payload["roomName"] = RoomName;
            payload["maxPlayers"] = MaxPlayers;
            payload["isPrivate"] = IsPrivate;
            return payload;
        }

        public static ShooterCreateOptionsMessage FromPayload(MsgMap payload)
        {
            var message = new ShooterCreateOptionsMessage();
            message.RoomName = payload.TryGetValue("roomName", out object? v0) && v0 != null
                ? (string?)(v0 as string ?? "")
                : null;
            message.MaxPlayers = (byte)Payloads.ToLong(payload["maxPlayers"]);
            message.IsPrivate = (payload["isPrivate"] is true);
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<ShooterCreateOptionsMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<ShooterCreateOptionsMessage>.Ok(FromPayload(decoded.Value)) : Result<ShooterCreateOptionsMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>shooterJoinOptions</c>.</summary>
    public sealed partial class ShooterJoinOptionsMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "shooterJoinOptions";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName,
            new MessageField("playerName", FieldType.String));

        /// <summary><c>playerName</c>: <c>string</c>.</summary>
        public string PlayerName { get; set; } = "";

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            payload["playerName"] = PlayerName;
            return payload;
        }

        public static ShooterJoinOptionsMessage FromPayload(MsgMap payload)
        {
            var message = new ShooterJoinOptionsMessage();
            message.PlayerName = (payload["playerName"] as string ?? "");
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<ShooterJoinOptionsMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<ShooterJoinOptionsMessage>.Ok(FromPayload(decoded.Value)) : Result<ShooterJoinOptionsMessage>.Fail(decoded.Error!);
        }
    }

    /// <summary>Contract message <c>startGame</c>.</summary>
    public sealed partial class StartGameMessage : IContractMessage
    {
        /// <summary>The message's name on the wire; its id comes from the handshake.</summary>
        public const string MessageName = "startGame";

        /// <summary>The declaration the codecs encode with.</summary>
        public static readonly MessageDef Definition = new MessageDef(MessageName);

        MessageDef IContractMessage.MessageDefinition => Definition;

        public MsgMap ToPayload()
        {
            var payload = new MsgMap();
            return payload;
        }

        public static StartGameMessage FromPayload(MsgMap payload)
        {
            var message = new StartGameMessage();
            return message;
        }

        /// <summary>Encodes with the room's codec.</summary>
        public Result<byte[]> Encode(IStateCodec codec) => codec.EncodeMessage(Definition, ToPayload());

        /// <summary>Decodes a body with the room's codec.</summary>
        public static Result<StartGameMessage> Decode(IStateCodec codec, byte[] body)
        {
            Result<MsgMap> decoded = codec.DecodeMessage(Definition, body, 0, body.Length);
            return decoded.IsOk ? Result<StartGameMessage>.Ok(FromPayload(decoded.Value)) : Result<StartGameMessage>.Fail(decoded.Error!);
        }
    }
}
