// <auto-generated>
// Generated by @bungohan/codegen from @bungohan/example-shooter-shared/src/index.ts (bungohan.v1).
// Do not edit: regenerate instead.
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Bungohan.Protocol;

namespace Bungohan.Example.Shooter
{
    /// <summary>Schema class <c>Bullet</c>.</summary>
    public sealed partial class Bullet : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "Bullet";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new Bullet(),
            new SchemaField("ownerId", "string"),
            new SchemaField("x", "fixed:1"),
            new SchemaField("y", "fixed:1"));

        public override SchemaClass Class => Definition;

        private string _ownerId = "";

        /// <summary><c>ownerId</c>: <c>string</c>.</summary>
        public string OwnerId => _ownerId;

        /// <summary>OwnerId changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? OwnerIdChanged;

        private double _x;

        /// <summary><c>x</c>: <c>fixed:1</c>.</summary>
        public double X => _x;

        /// <summary>X changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? XChanged;

        private double _y;

        /// <summary><c>y</c>: <c>fixed:1</c>.</summary>
        public double Y => _y;

        /// <summary>Y changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? YChanged;

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            0 => Apply(0, ref _ownerId, wire, changes, OwnerIdChanged),
            1 => Apply(1, ref _x, wire, changes, XChanged),
            2 => Apply(2, ref _y, wire, changes, YChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            _ => null,
        };
    }

    /// <summary>Schema class <c>Enemy</c>.</summary>
    public sealed partial class Enemy : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "Enemy";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new Enemy(),
            new SchemaField("x", "fixed:1"),
            new SchemaField("y", "fixed:1"),
            new SchemaField("health", "uint8"));

        public override SchemaClass Class => Definition;

        private double _x;

        /// <summary><c>x</c>: <c>fixed:1</c>.</summary>
        public double X => _x;

        /// <summary>X changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? XChanged;

        private double _y;

        /// <summary><c>y</c>: <c>fixed:1</c>.</summary>
        public double Y => _y;

        /// <summary>Y changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? YChanged;

        private byte _health;

        /// <summary><c>health</c>: <c>uint8</c>.</summary>
        public byte Health => _health;

        /// <summary>Health changed: (value, previous), after the frame is applied.</summary>
        public event Action<byte, byte>? HealthChanged;

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            0 => Apply(0, ref _x, wire, changes, XChanged),
            1 => Apply(1, ref _y, wire, changes, YChanged),
            2 => Apply(2, ref _health, wire, changes, HealthChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            _ => null,
        };
    }

    /// <summary>Schema class <c>GameState</c>.</summary>
    public sealed partial class GameState : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "GameState";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new GameState(),
            new SchemaField("players", "schemaMap<string,Player>"),
            new SchemaField("enemies", "schemaMap<uint32,Enemy>"),
            new SchemaField("bullets", "schemaMap<uint32,Bullet>"),
            new SchemaField("loot", "schemaMap<uint32,Loot>"),
            new SchemaField("roomCode", "string"),
            new SchemaField("roomName", "string"),
            new SchemaField("hostId", "string"),
            new SchemaField("gameTime", "uint16"),
            new SchemaField("gameStatus", "string"),
            new SchemaField("maxPlayers", "uint8"),
            new SchemaField("canStart", "bool"));

        public override SchemaClass Class => Definition;

        /// <summary><c>players</c>: <c>schemaMap&lt;string,Player&gt;</c>.</summary>
        public MapSchema<string, Player> Players { get; } = new MapSchema<string, Player>("schemaMap<string,Player>");

        /// <summary><c>enemies</c>: <c>schemaMap&lt;uint32,Enemy&gt;</c>.</summary>
        public MapSchema<uint, Enemy> Enemies { get; } = new MapSchema<uint, Enemy>("schemaMap<uint32,Enemy>");

        /// <summary><c>bullets</c>: <c>schemaMap&lt;uint32,Bullet&gt;</c>.</summary>
        public MapSchema<uint, Bullet> Bullets { get; } = new MapSchema<uint, Bullet>("schemaMap<uint32,Bullet>");

        /// <summary><c>loot</c>: <c>schemaMap&lt;uint32,Loot&gt;</c>.</summary>
        public MapSchema<uint, Loot> Loot { get; } = new MapSchema<uint, Loot>("schemaMap<uint32,Loot>");

        private string _roomCode = "";

        /// <summary><c>roomCode</c>: <c>string</c>.</summary>
        public string RoomCode => _roomCode;

        /// <summary>RoomCode changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? RoomCodeChanged;

        private string _roomName = "";

        /// <summary><c>roomName</c>: <c>string</c>.</summary>
        public string RoomName => _roomName;

        /// <summary>RoomName changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? RoomNameChanged;

        private string _hostId = "";

        /// <summary><c>hostId</c>: <c>string</c>.</summary>
        public string HostId => _hostId;

        /// <summary>HostId changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? HostIdChanged;

        private ushort _gameTime;

        /// <summary><c>gameTime</c>: <c>uint16</c>.</summary>
        public ushort GameTime => _gameTime;

        /// <summary>GameTime changed: (value, previous), after the frame is applied.</summary>
        public event Action<ushort, ushort>? GameTimeChanged;

        private string _gameStatus = "";

        /// <summary><c>gameStatus</c>: <c>string</c>.</summary>
        public string GameStatus => _gameStatus;

        /// <summary>GameStatus changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? GameStatusChanged;

        private byte _maxPlayers;

        /// <summary><c>maxPlayers</c>: <c>uint8</c>.</summary>
        public byte MaxPlayers => _maxPlayers;

        /// <summary>MaxPlayers changed: (value, previous), after the frame is applied.</summary>
        public event Action<byte, byte>? MaxPlayersChanged;

        private bool _canStart;

        /// <summary><c>canStart</c>: <c>bool</c>.</summary>
        public bool CanStart => _canStart;

        /// <summary>CanStart changed: (value, previous), after the frame is applied.</summary>
        public event Action<bool, bool>? CanStartChanged;

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            4 => Apply(4, ref _roomCode, wire, changes, RoomCodeChanged),
            5 => Apply(5, ref _roomName, wire, changes, RoomNameChanged),
            6 => Apply(6, ref _hostId, wire, changes, HostIdChanged),
            7 => Apply(7, ref _gameTime, wire, changes, GameTimeChanged),
            8 => Apply(8, ref _gameStatus, wire, changes, GameStatusChanged),
            9 => Apply(9, ref _maxPlayers, wire, changes, MaxPlayersChanged),
            10 => Apply(10, ref _canStart, wire, changes, CanStartChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            0 => Players,
            1 => Enemies,
            2 => Bullets,
            3 => Loot,
            _ => null,
        };
    }

    /// <summary>Schema class <c>LobbyState</c>.</summary>
    public sealed partial class LobbyState : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "LobbyState";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new LobbyState(),
            new SchemaField("rooms", "schemaMap<string,RoomInfo>"));

        public override SchemaClass Class => Definition;

        /// <summary><c>rooms</c>: <c>schemaMap&lt;string,RoomInfo&gt;</c>.</summary>
        public MapSchema<string, RoomInfo> Rooms { get; } = new MapSchema<string, RoomInfo>("schemaMap<string,RoomInfo>");

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            0 => Rooms,
            _ => null,
        };
    }

    /// <summary>Schema class <c>Loot</c>.</summary>
    public sealed partial class Loot : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "Loot";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new Loot(),
            new SchemaField("x", "fixed:1"),
            new SchemaField("y", "fixed:1"),
            new SchemaField("value", "uint8"));

        public override SchemaClass Class => Definition;

        private double _x;

        /// <summary><c>x</c>: <c>fixed:1</c>.</summary>
        public double X => _x;

        /// <summary>X changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? XChanged;

        private double _y;

        /// <summary><c>y</c>: <c>fixed:1</c>.</summary>
        public double Y => _y;

        /// <summary>Y changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? YChanged;

        private byte _value;

        /// <summary><c>value</c>: <c>uint8</c>.</summary>
        public byte Value => _value;

        /// <summary>Value changed: (value, previous), after the frame is applied.</summary>
        public event Action<byte, byte>? ValueChanged;

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            0 => Apply(0, ref _x, wire, changes, XChanged),
            1 => Apply(1, ref _y, wire, changes, YChanged),
            2 => Apply(2, ref _value, wire, changes, ValueChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            _ => null,
        };
    }

    /// <summary>Schema class <c>Player</c>.</summary>
    public sealed partial class Player : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "Player";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new Player(),
            new SchemaField("name", "string"),
            new SchemaField("color", "string"),
            new SchemaField("x", "fixed:1"),
            new SchemaField("y", "fixed:1"),
            new SchemaField("rotation", "fixed:2"),
            new SchemaField("score", "int32"),
            new SchemaField("health", "uint8"),
            new SchemaField("isDead", "bool"),
            new SchemaField("isReady", "bool"));

        public override SchemaClass Class => Definition;

        private string _name = "";

        /// <summary><c>name</c>: <c>string</c>.</summary>
        public string Name => _name;

        /// <summary>Name changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? NameChanged;

        private string _color = "";

        /// <summary><c>color</c>: <c>string</c>.</summary>
        public string Color => _color;

        /// <summary>Color changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? ColorChanged;

        private double _x;

        /// <summary><c>x</c>: <c>fixed:1</c>.</summary>
        public double X => _x;

        /// <summary>X changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? XChanged;

        private double _y;

        /// <summary><c>y</c>: <c>fixed:1</c>.</summary>
        public double Y => _y;

        /// <summary>Y changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? YChanged;

        private double _rotation;

        /// <summary><c>rotation</c>: <c>fixed:2</c>.</summary>
        public double Rotation => _rotation;

        /// <summary>Rotation changed: (value, previous), after the frame is applied.</summary>
        public event Action<double, double>? RotationChanged;

        private int _score;

        /// <summary><c>score</c>: <c>int32</c>.</summary>
        public int Score => _score;

        /// <summary>Score changed: (value, previous), after the frame is applied.</summary>
        public event Action<int, int>? ScoreChanged;

        private byte _health;

        /// <summary><c>health</c>: <c>uint8</c>.</summary>
        public byte Health => _health;

        /// <summary>Health changed: (value, previous), after the frame is applied.</summary>
        public event Action<byte, byte>? HealthChanged;

        private bool _isDead;

        /// <summary><c>isDead</c>: <c>bool</c>.</summary>
        public bool IsDead => _isDead;

        /// <summary>IsDead changed: (value, previous), after the frame is applied.</summary>
        public event Action<bool, bool>? IsDeadChanged;

        private bool _isReady;

        /// <summary><c>isReady</c>: <c>bool</c>.</summary>
        public bool IsReady => _isReady;

        /// <summary>IsReady changed: (value, previous), after the frame is applied.</summary>
        public event Action<bool, bool>? IsReadyChanged;

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            0 => Apply(0, ref _name, wire, changes, NameChanged),
            1 => Apply(1, ref _color, wire, changes, ColorChanged),
            2 => Apply(2, ref _x, wire, changes, XChanged),
            3 => Apply(3, ref _y, wire, changes, YChanged),
            4 => Apply(4, ref _rotation, wire, changes, RotationChanged),
            5 => Apply(5, ref _score, wire, changes, ScoreChanged),
            6 => Apply(6, ref _health, wire, changes, HealthChanged),
            7 => Apply(7, ref _isDead, wire, changes, IsDeadChanged),
            8 => Apply(8, ref _isReady, wire, changes, IsReadyChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            _ => null,
        };
    }

    /// <summary>Schema class <c>RoomInfo</c>.</summary>
    public sealed partial class RoomInfo : Schema
    {
        /// <summary>The class's name on the wire.</summary>
        public const string SchemaName = "RoomInfo";

        /// <summary>Fields and type strings, matched by name against the server's DEFINE.</summary>
        public static readonly SchemaClass Definition = new SchemaClass(SchemaName, () => new RoomInfo(),
            new SchemaField("name", "string"),
            new SchemaField("code", "string"),
            new SchemaField("hostName", "string"),
            new SchemaField("playerCount", "uint8"),
            new SchemaField("maxPlayers", "uint8"),
            new SchemaField("status", "string"));

        public override SchemaClass Class => Definition;

        private string _name = "";

        /// <summary><c>name</c>: <c>string</c>.</summary>
        public string Name => _name;

        /// <summary>Name changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? NameChanged;

        private string _code = "";

        /// <summary><c>code</c>: <c>string</c>.</summary>
        public string Code => _code;

        /// <summary>Code changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? CodeChanged;

        private string _hostName = "";

        /// <summary><c>hostName</c>: <c>string</c>.</summary>
        public string HostName => _hostName;

        /// <summary>HostName changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? HostNameChanged;

        private byte _playerCount;

        /// <summary><c>playerCount</c>: <c>uint8</c>.</summary>
        public byte PlayerCount => _playerCount;

        /// <summary>PlayerCount changed: (value, previous), after the frame is applied.</summary>
        public event Action<byte, byte>? PlayerCountChanged;

        private byte _maxPlayers;

        /// <summary><c>maxPlayers</c>: <c>uint8</c>.</summary>
        public byte MaxPlayers => _maxPlayers;

        /// <summary>MaxPlayers changed: (value, previous), after the frame is applied.</summary>
        public event Action<byte, byte>? MaxPlayersChanged;

        private string _status = "";

        /// <summary><c>status</c>: <c>string</c>.</summary>
        public string Status => _status;

        /// <summary>Status changed: (value, previous), after the frame is applied.</summary>
        public event Action<string, string>? StatusChanged;

        protected override bool ApplyField(int index, object? wire, ChangeQueue? changes) => index switch
        {
            0 => Apply(0, ref _name, wire, changes, NameChanged),
            1 => Apply(1, ref _code, wire, changes, CodeChanged),
            2 => Apply(2, ref _hostName, wire, changes, HostNameChanged),
            3 => Apply(3, ref _playerCount, wire, changes, PlayerCountChanged),
            4 => Apply(4, ref _maxPlayers, wire, changes, MaxPlayersChanged),
            5 => Apply(5, ref _status, wire, changes, StatusChanged),
            _ => false,
        };

        protected override object? GetChild(int index) => index switch
        {
            _ => null,
        };
    }

    /// <summary>Every generated schema class.</summary>
    public static class Schemas
    {
        /// <summary>Registers every class, so the replica can instantiate what the server sends.</summary>
        public static SchemaRegistry Register(SchemaRegistry registry)
        {
            registry.Register(Bullet.Definition);
            registry.Register(Enemy.Definition);
            registry.Register(GameState.Definition);
            registry.Register(LobbyState.Definition);
            registry.Register(Loot.Definition);
            registry.Register(Player.Definition);
            registry.Register(RoomInfo.Definition);
            return registry;
        }

        public static SchemaRegistry CreateRegistry() => Register(new SchemaRegistry());
    }
}
